import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Printer, Download } from "lucide-react";
import { toast } from "sonner";
import { bookings } from "@/mocks/bookings";

export interface InvoiceData {
  invoiceNo: string;
  period: string;
  status: "Issued" | "Paid" | "Overdue" | "Partial";
  supplyAmount: number;
  vat: number;
  total: number;
  issuedDate: string;
  dueDate: string;
}

interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  invoice: InvoiceData | null;
}

type Lang = "EN" | "KO" | "JA" | "ZH" | "VI";

/* Translations */
const L: Record<string, Record<Lang, string>> = {
  invoice: { EN: "INVOICE", KO: "세금계산서", JA: "請求書", ZH: "发票", VI: "HÓA ĐƠN" },
  invoiceNo: { EN: "Invoice No.", KO: "인보이스 번호", JA: "請求書番号", ZH: "发票号码", VI: "Số hóa đơn" },
  issueDate: { EN: "Issue Date", KO: "발행일", JA: "発行日", ZH: "开票日期", VI: "Ngày phát hành" },
  dueDate: { EN: "Due Date", KO: "납부 기한", JA: "支払期日", ZH: "付款期限", VI: "Hạn thanh toán" },
  period: { EN: "Billing Period", KO: "청구 기간", JA: "請求期間", ZH: "账单周期", VI: "Kỳ thanh toán" },
  status: { EN: "Status", KO: "상태", JA: "ステータス", ZH: "状态", VI: "Trạng thái" },
  supplier: { EN: "Supplier (공급자)", KO: "공급자", JA: "供給者", ZH: "供应商", VI: "Nhà cung cấp" },
  customer: { EN: "Customer (공급받는자)", KO: "공급받는자", JA: "顧客", ZH: "客户", VI: "Khách hàng" },
  companyName: { EN: "Company Name", KO: "회사명", JA: "会社名", ZH: "公司名称", VI: "Tên công ty" },
  regNo: { EN: "Business Reg. No.", KO: "사업자 등록번호", JA: "事業者登録番号", ZH: "营业执照号", VI: "Mã số kinh doanh" },
  ceo: { EN: "CEO", KO: "대표자", JA: "代表者", ZH: "法人代表", VI: "Giám đốc" },
  address: { EN: "Address", KO: "주소", JA: "住所", ZH: "地址", VI: "Địa chỉ" },
  businessType: { EN: "Business Type", KO: "업태", JA: "業種", ZH: "行业", VI: "Loại hình KD" },
  items: { EN: "Booking Items", KO: "예약 내역", JA: "予約項目", ZH: "预订项目", VI: "Mục đặt phòng" },
  itemNo: { EN: "No.", KO: "번호", JA: "番号", ZH: "编号", VI: "STT" },
  bookingId: { EN: "Booking ID", KO: "예약번호", JA: "予約ID", ZH: "预订号", VI: "Mã đặt phòng" },
  hotel: { EN: "Hotel", KO: "호텔", JA: "ホテル", ZH: "酒店", VI: "Khách sạn" },
  checkIn: { EN: "Check-In", KO: "체크인", JA: "チェックイン", ZH: "入住", VI: "Nhận phòng" },
  nights: { EN: "Nts", KO: "박", JA: "泊", ZH: "晚", VI: "đêm" },
  guest: { EN: "Guest", KO: "투숙객", JA: "宿泊者", ZH: "客人", VI: "Khách" },
  amount: { EN: "Amount", KO: "금액", JA: "金額", ZH: "金额", VI: "Số tiền" },
  summary: { EN: "Summary", KO: "합계", JA: "合計", ZH: "汇总", VI: "Tổng kết" },
  subtotal: { EN: "Subtotal", KO: "공급가액", JA: "小計", ZH: "小计", VI: "Tạm tính" },
  vat: { EN: "VAT (10%)", KO: "부가세 (10%)", JA: "消費税 (10%)", ZH: "增值税 (10%)", VI: "VAT (10%)" },
  total: { EN: "Total Due", KO: "총 납부금액", JA: "合計金額", ZH: "应付总额", VI: "Tổng cộng" },
  bank: { EN: "Payment Information", KO: "결제 정보", JA: "支払情報", ZH: "付款信息", VI: "Thông tin thanh toán" },
  bankName: { EN: "Bank", KO: "은행", JA: "銀行", ZH: "银行", VI: "Ngân hàng" },
  accountNo: { EN: "Account No.", KO: "계좌번호", JA: "口座番号", ZH: "账号", VI: "Số tài khoản" },
  accountHolder: { EN: "Account Holder", KO: "예금주", JA: "名義人", ZH: "户主", VI: "Chủ tài khoản" },
  note: { EN: "Notes", KO: "비고", JA: "備考", ZH: "备注", VI: "Ghi chú" },
  noteText: {
    EN: "Please remit the total amount by the due date. Late payments may incur interest charges as per the service agreement.",
    KO: "납부 기한까지 총 금액을 송금해 주시기 바랍니다. 연체 시 서비스 계약서에 따라 이자가 부과될 수 있습니다.",
    JA: "支払期日までに合計金額をご送金ください。遅延の場合、サービス契約に基づき利息が発生する可能性があります。",
    ZH: "请在付款期限前汇款。如有逾期，可能会根据服务协议产生利息。",
    VI: "Vui lòng chuyển toàn bộ số tiền trước hạn. Thanh toán trễ có thể phát sinh lãi theo hợp đồng dịch vụ.",
  },
  generated: { EN: "Generated by DOTBIZ Platform", KO: "DOTBIZ 플랫폼에서 발행됨", JA: "DOTBIZプラットフォームにより発行", ZH: "由DOTBIZ平台生成", VI: "Được tạo bởi DOTBIZ Platform" },
};

export default function InvoicePreviewDialog({ open, onOpenChange, invoice }: Props) {
  const [lang, setLang] = useState<Lang>("EN");
  const [showLogo, setShowLogo] = useState(true);
  const [showBankInfo, setShowBankInfo] = useState(true);

  const t = (k: string) => L[k]?.[lang] || L[k]?.EN || k;

  if (!invoice) return null;

  /* Pick sample bookings for this invoice period */
  const sampleBookings = bookings.slice(0, 5).map((b, i) => ({
    no: i + 1,
    bookingId: b.ellisCode,
    hotel: b.hotelName,
    checkIn: b.checkIn,
    nights: b.nights,
    guest: b.traveler,
    amount: b.sumAmount,
  }));
  const itemsTotal = sampleBookings.reduce((s, b) => s + b.amount, 0);
  /* Scale sample items to match invoice total */
  const scale = invoice.supplyAmount / itemsTotal;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[95vh] overflow-y-auto p-0" style={{ maxWidth: "900px", width: "90vw" }}>
        <DialogHeader className="px-6 pt-4 pb-2 border-b"><DialogTitle>Invoice Preview</DialogTitle></DialogHeader>

        {/* Options Bar (non-printable) */}
        <div className="px-6 py-3 border-b flex items-center gap-6 flex-wrap bg-muted/30 no-print">
          <label className="flex items-center gap-2 text-sm cursor-pointer">
            <Checkbox checked={showLogo} onCheckedChange={c => setShowLogo(!!c)} />
            Show OhMyHotel info
          </label>
          <label className="flex items-center gap-2 text-sm cursor-pointer">
            <Checkbox checked={showBankInfo} onCheckedChange={c => setShowBankInfo(!!c)} />
            Show bank account
          </label>
          <div className="flex items-center gap-2 text-sm">
            <span className="text-muted-foreground">Language:</span>
            {(["EN", "KO", "JA", "ZH", "VI"] as const).map(l => (
              <label key={l} className="flex items-center gap-1 cursor-pointer">
                <input type="radio" name="invoiceLang" checked={lang === l} onChange={() => setLang(l)} className="accent-[#FF6000]" />
                <span className={lang === l ? "text-[#FF6000] font-medium" : ""}>{l}</span>
              </label>
            ))}
          </div>
        </div>

        {/* A4 Invoice */}
        <div id="printable-voucher" className="bg-white text-slate-900 p-10" style={{ fontFamily: "Arial, sans-serif" }}>
          {/* Header */}
          <div className="flex items-start justify-between mb-6 pb-4 border-b-4" style={{ borderColor: "#FF6000" }}>
            <div>
              {showLogo && (
                <div className="flex items-center gap-2 mb-2">
                  <div className="relative w-10 h-10 shrink-0">
                    <div className="absolute inset-0 rounded-full" style={{ background: "conic-gradient(from 180deg, #FF6000, #FF8C00, #FFCF8F, #FF6000)" }} />
                    <div className="absolute inset-[2px] rounded-full bg-white flex items-center justify-center">
                      <svg viewBox="0 0 24 24" className="w-5 h-5" fill="none"><path d="M12 3C7.5 3 4 6.5 4 11c0 3 1.5 5.5 4 7l1-2c-2-1-3-3-3-5 0-3.3 2.7-6 6-6s6 2.7 6 6c0 2-1 3.8-2.5 5l1 2c2.3-1.5 3.5-4 3.5-7 0-4.5-3.5-8-8-8z" fill="#FF6000" /><circle cx="12" cy="4" r="2.5" fill="#009505" /></svg>
                    </div>
                  </div>
                  <span className="text-xl font-bold" style={{ color: "#FF6000" }}>DOTBIZ</span>
                </div>
              )}
              <h1 className="text-4xl font-bold tracking-wider" style={{ color: "#1a1a2e" }}>{t("invoice")}</h1>
              <p className="text-xs text-slate-500 mt-1">{t("generated")}</p>
            </div>
            <div className="text-right text-sm">
              <p className="text-slate-500 text-xs uppercase">{t("invoiceNo")}</p>
              <p className="font-mono font-bold text-lg" style={{ color: "#FF6000" }}>{invoice.invoiceNo}</p>
              <div className="mt-3 space-y-0.5 text-xs">
                <p><span className="text-slate-500">{t("issueDate")}:</span> <span className="font-medium">{invoice.issuedDate}</span></p>
                <p><span className="text-slate-500">{t("dueDate")}:</span> <span className={`font-medium ${invoice.status === "Overdue" ? "text-red-600" : ""}`}>{invoice.dueDate}</span></p>
                <p><span className="text-slate-500">{t("period")}:</span> <span className="font-medium">{invoice.period}</span></p>
                <p><span className="text-slate-500">{t("status")}:</span> <span className={`font-bold ${invoice.status === "Paid" ? "text-green-600" : invoice.status === "Overdue" ? "text-red-600" : "text-orange-600"}`}>{invoice.status}</span></p>
              </div>
            </div>
          </div>

          {/* Supplier & Customer */}
          <div className="grid grid-cols-2 gap-6 mb-6">
            <div className="border rounded p-4 bg-slate-50">
              <h3 className="text-xs font-bold text-slate-500 uppercase mb-2">{t("supplier")}</h3>
              <div className="space-y-1 text-sm">
                <p className="font-bold text-base">OhMyHotel Global Pte. Ltd.</p>
                <p><span className="text-slate-500 text-xs">{t("regNo")}:</span> 202543984E</p>
                <p><span className="text-slate-500 text-xs">{t("ceo")}:</span> Lee Misoon</p>
                <p><span className="text-slate-500 text-xs">{t("address")}:</span> 111 Somerset Road, #06-01H, Singapore 238164</p>
                <p><span className="text-slate-500 text-xs">{t("businessType")}:</span> Travel Services / Hotel Booking B2B</p>
              </div>
            </div>
            <div className="border rounded p-4 bg-orange-50">
              <h3 className="text-xs font-bold text-slate-500 uppercase mb-2">{t("customer")}</h3>
              <div className="space-y-1 text-sm">
                <p className="font-bold text-base">TravelCo International</p>
                <p><span className="text-slate-500 text-xs">{t("regNo")}:</span> 123-45-67890</p>
                <p><span className="text-slate-500 text-xs">{t("ceo")}:</span> James Park</p>
                <p><span className="text-slate-500 text-xs">{t("address")}:</span> 123 Gangnam-daero, Seoul</p>
                <p><span className="text-slate-500 text-xs">{t("businessType")}:</span> Travel Agency</p>
              </div>
            </div>
          </div>

          {/* Booking Items Table */}
          <h3 className="text-sm font-bold uppercase mb-2" style={{ color: "#FF6000" }}>{t("items")}</h3>
          <table className="w-full mb-6 text-sm border">
            <thead>
              <tr className="bg-slate-100 border-b-2" style={{ borderColor: "#1a1a2e" }}>
                <th className="py-2 px-3 text-left text-xs font-bold">{t("itemNo")}</th>
                <th className="py-2 px-3 text-left text-xs font-bold">{t("bookingId")}</th>
                <th className="py-2 px-3 text-left text-xs font-bold">{t("hotel")}</th>
                <th className="py-2 px-3 text-left text-xs font-bold">{t("checkIn")}</th>
                <th className="py-2 px-3 text-center text-xs font-bold">{t("nights")}</th>
                <th className="py-2 px-3 text-left text-xs font-bold">{t("guest")}</th>
                <th className="py-2 px-3 text-right text-xs font-bold">{t("amount")}</th>
              </tr>
            </thead>
            <tbody>
              {sampleBookings.map((b, i) => (
                <tr key={b.no} className={i % 2 === 0 ? "bg-white" : "bg-slate-50"}>
                  <td className="py-2 px-3 text-center">{b.no}</td>
                  <td className="py-2 px-3 font-mono text-xs">{b.bookingId}</td>
                  <td className="py-2 px-3">{b.hotel}</td>
                  <td className="py-2 px-3 text-xs">{b.checkIn}</td>
                  <td className="py-2 px-3 text-center">{b.nights}</td>
                  <td className="py-2 px-3 text-xs">{b.guest}</td>
                  <td className="py-2 px-3 text-right font-medium">USD {(b.amount * scale).toFixed(2)}</td>
                </tr>
              ))}
            </tbody>
          </table>

          {/* Summary */}
          <div className="flex justify-end mb-6">
            <div className="w-80 border rounded overflow-hidden">
              <h3 className="px-4 py-2 text-xs font-bold uppercase" style={{ background: "#1a1a2e", color: "white" }}>{t("summary")}</h3>
              <div className="p-4 space-y-2 text-sm">
                <div className="flex justify-between"><span className="text-slate-600">{t("subtotal")}</span><span className="font-medium">USD {invoice.supplyAmount.toLocaleString()}</span></div>
                <div className="flex justify-between"><span className="text-slate-600">{t("vat")}</span><span className="font-medium">USD {invoice.vat.toLocaleString()}</span></div>
                <div className="h-px bg-slate-300 my-2" />
                <div className="flex justify-between text-base">
                  <span className="font-bold">{t("total")}</span>
                  <span className="font-bold" style={{ color: "#FF6000" }}>USD {invoice.total.toLocaleString()}</span>
                </div>
              </div>
            </div>
          </div>

          {/* Bank Info */}
          {showBankInfo && (
            <div className="border rounded p-4 mb-4 bg-slate-50">
              <h3 className="text-xs font-bold uppercase mb-2" style={{ color: "#FF6000" }}>{t("bank")}</h3>
              <div className="grid grid-cols-3 gap-4 text-sm">
                <div><p className="text-xs text-slate-500">{t("bankName")}</p><p className="font-medium">DBS Bank Singapore</p></div>
                <div><p className="text-xs text-slate-500">{t("accountNo")}</p><p className="font-mono font-medium">012-345678-9</p></div>
                <div><p className="text-xs text-slate-500">{t("accountHolder")}</p><p className="font-medium">OhMyHotel Global Pte. Ltd.</p></div>
              </div>
            </div>
          )}

          {/* Notes */}
          <div className="border-l-4 pl-4 py-2" style={{ borderColor: "#FF6000" }}>
            <p className="text-xs font-bold uppercase mb-1" style={{ color: "#FF6000" }}>{t("note")}</p>
            <p className="text-xs text-slate-700">{t("noteText")}</p>
          </div>

          {/* Footer */}
          <div className="mt-8 pt-4 border-t text-center">
            <p className="text-[10px] text-slate-500">OHMYHOTEL & CO., Ltd. (105-87-71311) · GT Dongdaemun Building 6F, Jongno-gu, Seoul · Tel: +82-2-762-0552</p>
            <p className="text-[10px] text-slate-500 mt-1">© 2026 OHMYHOTEL GLOBAL PTE. LTD. All rights reserved.</p>
          </div>
        </div>

        {/* Footer actions */}
        <div className="flex justify-end gap-2 px-6 py-3 border-t bg-muted/30 sticky bottom-0 no-print">
          <Button variant="outline" onClick={() => onOpenChange(false)}>Close</Button>
          <Button variant="outline" onClick={() => toast.success("Invoice sent to client's email")}>
            <Download className="h-4 w-4 mr-1" />Email Invoice
          </Button>
          <Button style={{ background: "#FF6000" }} onClick={() => window.print()}>
            <Printer className="h-4 w-4 mr-1" />Print / Save PDF
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
