import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Printer, Download } from "lucide-react";
import { toast } from "sonner";
import { bookings } from "@/mocks/bookings";
import { currentCompany, type Company } from "@/mocks/companies";

export interface InvoiceData {
  invoiceNo: string;
  period: string;
  status: "Issued" | "Paid" | "Overdue" | "Partial";
  supplyAmount: number;
  vat: number;
  total: number;
  issuedDate: string;
  dueDate: string;
}

interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  invoice: InvoiceData | null;
  customer?: Company;  /* Optional — falls back to currentCompany */
}

/* OhMyHotel (seller) taxProfile — acts as supplier for all invoices */
const SELLER_PROFILE = {
  country: "KR" as const,
  taxId: "105-87-71311",
  legalName: "OHMYHOTEL & CO., LTD.",
  vatScheme: "Standard" as const,
  registeredForEInvoice: true,
  reverseChargeApplicable: false,
  currency: "KRW",
};

type Lang = "EN" | "KO" | "JA" | "ZH" | "VI";

/* Translations */
const L: Record<string, Record<Lang, string>> = {
  invoice: { EN: "INVOICE", KO: "세금계산서", JA: "請求書", ZH: "发票", VI: "HÓA ĐƠN" },
  invoiceNo: { EN: "Invoice No.", KO: "인보이스 번호", JA: "請求書番号", ZH: "发票号码", VI: "Số hóa đơn" },
  issueDate: { EN: "Issue Date", KO: "발행일", JA: "発行日", ZH: "开票日期", VI: "Ngày phát hành" },
  dueDate: { EN: "Due Date", KO: "납부 기한", JA: "支払期日", ZH: "付款期限", VI: "Hạn thanh toán" },
  period: { EN: "Billing Period", KO: "청구 기간", JA: "請求期間", ZH: "账单周期", VI: "Kỳ thanh toán" },
  status: { EN: "Status", KO: "상태", JA: "ステータス", ZH: "状态", VI: "Trạng thái" },
  supplier: { EN: "Supplier", KO: "공급자", JA: "供給者", ZH: "供应商", VI: "Nhà cung cấp" },
  customer: { EN: "Customer", KO: "공급받는자", JA: "顧客", ZH: "客户", VI: "Khách hàng" },
  companyName: { EN: "Company Name", KO: "회사명", JA: "会社名", ZH: "公司名称", VI: "Tên công ty" },
  regNo: { EN: "Business Reg. No.", KO: "사업자 등록번호", JA: "事業者登録番号", ZH: "营业执照号", VI: "Mã số kinh doanh" },
  ceo: { EN: "CEO", KO: "대표자", JA: "代表者", ZH: "法人代表", VI: "Giám đốc" },
  address: { EN: "Address", KO: "주소", JA: "住所", ZH: "地址", VI: "Địa chỉ" },
  businessType: { EN: "Business Type", KO: "업태", JA: "業種", ZH: "行业", VI: "Loại hình KD" },
  items: { EN: "Booking Items", KO: "예약 내역", JA: "予約項目", ZH: "预订项目", VI: "Mục đặt phòng" },
  itemNo: { EN: "No.", KO: "번호", JA: "番号", ZH: "编号", VI: "STT" },
  bookingId: { EN: "Booking ID", KO: "예약번호", JA: "予約ID", ZH: "预订号", VI: "Mã đặt phòng" },
  hotel: { EN: "Hotel", KO: "호텔", JA: "ホテル", ZH: "酒店", VI: "Khách sạn" },
  checkIn: { EN: "Check-In", KO: "체크인", JA: "チェックイン", ZH: "入住", VI: "Nhận phòng" },
  nights: { EN: "Nts", KO: "박", JA: "泊", ZH: "晚", VI: "đêm" },
  guest: { EN: "Guest", KO: "투숙객", JA: "宿泊者", ZH: "客人", VI: "Khách" },
  amount: { EN: "Amount", KO: "금액", JA: "金額", ZH: "金额", VI: "Số tiền" },
  summary: { EN: "Summary", KO: "합계", JA: "合計", ZH: "汇总", VI: "Tổng kết" },
  subtotal: { EN: "Subtotal", KO: "공급가액", JA: "小計", ZH: "小计", VI: "Tạm tính" },
  vat: { EN: "VAT (10%)", KO: "부가세 (10%)", JA: "消費税 (10%)", ZH: "增值税 (10%)", VI: "VAT (10%)" },
  total: { EN: "Total Due", KO: "총 납부금액", JA: "合計金額", ZH: "应付总额", VI: "Tổng cộng" },
  bank: { EN: "Payment Information", KO: "결제 정보", JA: "支払情報", ZH: "付款信息", VI: "Thông tin thanh toán" },
  bankName: { EN: "Bank", KO: "은행", JA: "銀行", ZH: "银行", VI: "Ngân hàng" },
  accountNo: { EN: "Account No.", KO: "계좌번호", JA: "口座番号", ZH: "账号", VI: "Số tài khoản" },
  accountHolder: { EN: "Account Holder", KO: "예금주", JA: "名義人", ZH: "户主", VI: "Chủ tài khoản" },
  note: { EN: "Notes", KO: "비고", JA: "備考", ZH: "备注", VI: "Ghi chú" },
  noteText: {
    EN: "Please remit the total amount by the due date. Late payments may incur interest charges as per the service agreement.",
    KO: "납부 기한까지 총 금액을 송금해 주시기 바랍니다. 연체 시 서비스 계약서에 따라 이자가 부과될 수 있습니다.",
    JA: "支払期日までに合計金額をご送金ください。遅延の場合、サービス契約に基づき利息が発生する可能性があります。",
    ZH: "请在付款期限前汇款。如有逾期，可能会根据服务协议产生利息。",
    VI: "Vui lòng chuyển toàn bộ số tiền trước hạn. Thanh toán trễ có thể phát sinh lãi theo hợp đồng dịch vụ.",
  },
  generated: { EN: "Generated by DOTBIZ Platform", KO: "DOTBIZ 플랫폼에서 발행됨", JA: "DOTBIZプラットフォームにより発行", ZH: "由DOTBIZ平台生成", VI: "Được tạo bởi DOTBIZ Platform" },
};

export default function InvoicePreviewDialog({ open, onOpenChange, invoice, customer }: Props) {
  const [lang, setLang] = useState<Lang>("EN");
  const [showLogo, setShowLogo] = useState(true);
  const [showBankInfo, setShowBankInfo] = useState(true);

  const t = (k: string) => L[k]?.[lang] || L[k]?.EN || k;

  const activeCustomer: Company = customer || currentCompany;

  if (!invoice) return null;

  /* Policy: booking price is the all-in final (VAT internally included).
   *         Invoice total = sum of booking amounts — customer wires the exact amount.
   */

  /* Pick sample bookings for this invoice period */
  const sampleBookings = bookings.slice(0, 5).map((b, i) => ({
    no: i + 1,
    bookingId: b.ellisCode,
    hotel: b.hotelName,
    checkIn: b.checkIn,
    nights: b.nights,
    guest: b.traveler,
    amount: b.sumAmount,
  }));
  const itemsTotal = sampleBookings.reduce((s, b) => s + b.amount, 0);
  /* Scale sample items to match invoice total */
  const scale = invoice.supplyAmount / itemsTotal;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[95vh] overflow-y-auto p-0" style={{ maxWidth: "900px", width: "90vw" }}>
        <DialogHeader className="px-6 pt-4 pb-2 border-b"><DialogTitle>Invoice Preview</DialogTitle></DialogHeader>

        {/* Options Bar (non-printable) */}
        <div className="px-6 py-3 border-b flex items-center gap-6 flex-wrap bg-muted/30 no-print">
          <label className="flex items-center gap-2 text-sm cursor-pointer">
            <Checkbox checked={showLogo} onCheckedChange={c => setShowLogo(!!c)} />
            Show OhMyHotel info
          </label>
          <label className="flex items-center gap-2 text-sm cursor-pointer">
            <Checkbox checked={showBankInfo} onCheckedChange={c => setShowBankInfo(!!c)} />
            Show bank account
          </label>
          <div className="flex items-center gap-2 text-sm">
            <span className="text-muted-foreground">Language:</span>
            {(["EN", "KO", "JA", "ZH", "VI"] as const).map(l => (
              <label key={l} className="flex items-center gap-1 cursor-pointer">
                <input type="radio" name="invoiceLang" checked={lang === l} onChange={() => setLang(l)} className="accent-[#FF6000]" />
                <span className={lang === l ? "text-[#FF6000] font-medium" : ""}>{l}</span>
              </label>
            ))}
          </div>
        </div>

        {/* A4 Invoice — clean sample style (matches reference 765887) */}
        <div id="printable-voucher" className="bg-white text-slate-900 p-12" style={{ fontFamily: "Arial, sans-serif" }}>
          {/* Header: Logo + Invoice No box */}
          <div className="flex items-start justify-between mb-8">
            <div>
              {showLogo && (
                <div className="flex items-center gap-2 mb-6">
                  <div className="relative w-8 h-8 shrink-0">
                    <div className="absolute inset-0 rounded-full" style={{ background: "conic-gradient(from 180deg, #FF6000, #FF8C00, #FFCF8F, #FF6000)" }} />
                    <div className="absolute inset-[2px] rounded-full bg-white flex items-center justify-center">
                      <svg viewBox="0 0 24 24" className="w-4 h-4" fill="none"><path d="M12 3C7.5 3 4 6.5 4 11c0 3 1.5 5.5 4 7l1-2c-2-1-3-3-3-5 0-3.3 2.7-6 6-6s6 2.7 6 6c0 2-1 3.8-2.5 5l1 2c2.3-1.5 3.5-4 3.5-7 0-4.5-3.5-8-8-8z" fill="#FF6000" /><circle cx="12" cy="4" r="2.5" fill="#009505" /></svg>
                    </div>
                  </div>
                  <span className="text-xl font-bold" style={{ color: "#FF6000" }}>OHMYHOTEL</span>
                </div>
              )}
              <h1 className="text-4xl font-bold text-slate-900">{t("invoice")}</h1>
            </div>
            <div className="border border-slate-300 rounded px-5 py-3 text-right min-w-[220px]">
              <p className="text-xs text-slate-500 uppercase">{t("invoiceNo")}</p>
              <p className="font-bold text-2xl">{invoice.invoiceNo}</p>
              <div className="mt-2 text-[11px] text-slate-600">
                <p><span className="font-medium">{t("issueDate")}:</span> {invoice.issuedDate}</p>
                <p><span className="font-medium">{t("dueDate")}:</span> {invoice.dueDate}</p>
              </div>
            </div>
          </div>

          {/* Bill To / From */}
          <div className="grid grid-cols-2 gap-8 mb-6">
            <div>
              <h3 className="text-xs font-bold text-slate-500 uppercase mb-2">Bill To</h3>
              <p className="font-semibold text-sm">{activeCustomer.name}</p>
              <p className="text-xs text-slate-600 mt-0.5">{activeCustomer.address}</p>
              <p className="text-xs text-slate-600">Reg. {activeCustomer.businessRegNo}</p>
            </div>
            <div>
              <h3 className="text-xs font-bold text-slate-500 uppercase mb-2">From</h3>
              <p className="font-semibold text-sm">Ohmyhotel SG</p>
              <p className="text-xs text-slate-600 mt-0.5">OhMyHotel Global Pte. Ltd.</p>
              <p className="text-xs text-slate-600">Reg. 202543984E</p>
            </div>
          </div>

          {/* Currency / Total / Check Out + Approved by (with seal) */}
          <div className="grid grid-cols-[1fr_auto] gap-8 mb-8">
            <div className="grid grid-cols-2 gap-6">
              <div>
                <p className="text-xs text-slate-500 uppercase">Currency</p>
                <p className="font-semibold text-sm mt-1">{activeCustomer.contractCurrency}</p>
              </div>
              <div>
                <p className="text-xs text-slate-500 uppercase">Total Amount</p>
                <p className="font-semibold text-sm mt-1">{activeCustomer.contractCurrency} {invoice.total.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</p>
              </div>
              <div className="col-span-2">
                <p className="text-xs text-slate-500 uppercase">Check Out (Period)</p>
                <p className="font-semibold text-sm mt-1">{invoice.period}</p>
              </div>
            </div>
            {/* Approved by (signature + seal) */}
            <div className="relative w-48 flex flex-col items-center justify-end">
              <div className="relative w-full h-20">
                {/* Seal circle */}
                <div className="absolute right-0 top-0 w-24 h-24 rounded-full border-[3px] flex items-center justify-center" style={{ borderColor: "#1e3a8a", opacity: 0.8 }}>
                  <div className="absolute inset-2 rounded-full border border-blue-900 opacity-60" />
                  <span className="text-[8px] font-bold text-blue-900 text-center leading-tight">OHMYHOTEL<br/>GLOBAL<br/>PTE. LTD.<br/><span className="text-[7px]">202543984E</span></span>
                  <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-blue-900 text-xl">★</div>
                </div>
                {/* Signature scribble */}
                <svg viewBox="0 0 120 40" className="absolute left-0 bottom-0 w-24 h-10">
                  <path d="M5 30 Q 20 10 35 25 T 65 20 T 95 25" stroke="#1e3a8a" strokeWidth="1.5" fill="none" />
                  <path d="M15 28 L 50 15" stroke="#1e3a8a" strokeWidth="1" fill="none" />
                </svg>
              </div>
              <p className="text-xs text-slate-500 mt-2 border-t border-slate-300 pt-1 w-full text-center">Approved by</p>
            </div>
          </div>

          {/* Items table — simple Qty/Price style (matches sample) */}
          <table className="w-full mb-6 text-sm">
            <thead>
              <tr className="border-b-2 border-slate-900">
                <th className="py-2 text-left text-xs font-bold w-8">#</th>
                <th className="py-2 text-left text-xs font-bold">Description</th>
                <th className="py-2 text-right text-xs font-bold">Qty</th>
                <th className="py-2 text-right text-xs font-bold">Price</th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-b border-slate-200">
                <td className="py-3">1</td>
                <td className="py-3">Reservation</td>
                <td className="py-3 text-right">{invoice.bookingIds.length || sampleBookings.length}</td>
                <td className="py-3 text-right">{activeCustomer.contractCurrency} {invoice.total.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td>
              </tr>
              <tr className="border-b border-slate-200">
                <td className="py-3">2</td>
                <td className="py-3">Cancellation Fee</td>
                <td className="py-3 text-right">0</td>
                <td className="py-3 text-right">{activeCustomer.contractCurrency} 0.00</td>
              </tr>
            </tbody>
          </table>

          {/* Totals panel */}
          <div className="bg-slate-100 rounded p-4 mb-6">
            <div className="flex justify-between items-center mb-1">
              <span className="text-sm text-slate-700">Total Amount</span>
              <span className="font-bold text-base">{activeCustomer.contractCurrency} {invoice.total.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
            </div>
            <div className="flex justify-between items-center mb-1">
              <span className="text-sm text-slate-700">Total Paid</span>
              <span className="text-base text-slate-700">-{activeCustomer.contractCurrency} {(invoice.receivedAmount || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
            </div>
            <div className="h-px bg-slate-300 my-2" />
            <div className="flex justify-between items-center">
              <span className="font-bold text-red-600">Balance</span>
              <span className="font-bold text-red-600 text-lg">{activeCustomer.contractCurrency} {(invoice.total - (invoice.receivedAmount || 0)).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
            </div>
          </div>

          <p className="text-[10px] text-slate-500 mb-8">* Tax included. Customer remits the exact amount in contract currency.</p>

          {/* Bank Info + Thank You */}
          {showBankInfo && (
            <div className="mb-6">
              <p className="text-sm"><span className="font-bold">Bank Account:</span> Citi Bank / OHMYHOTEL GLOBAL PTE. LTD. / 143746003</p>
            </div>
          )}

          <p className="text-center text-2xl font-medium text-slate-700 my-8">Thank you for your business</p>

          {/* Footer */}
          <div className="pt-4 border-t text-center">
            <p className="text-xs text-slate-600">111 Somerset Road, #06-01H, 111 Somerset, Singapore 238164</p>
            <p className="text-xs text-slate-500 mt-0.5">Tel: / Fax:</p>
            <p className="text-[10px] text-slate-400 mt-2">© 2026 OHMYHOTEL GLOBAL PTE. LTD. All rights reserved.</p>
          </div>
        </div>

        {/* Footer actions */}
        <div className="flex justify-end gap-2 px-6 py-3 border-t bg-muted/30 sticky bottom-0 no-print">
          <Button variant="outline" onClick={() => onOpenChange(false)}>Close</Button>
          <Button variant="outline" onClick={() => toast.success("Invoice sent to client's email")}>
            <Download className="h-4 w-4 mr-1" />Email Invoice
          </Button>
          <Button style={{ background: "#FF6000" }} onClick={() => window.print()}>
            <Printer className="h-4 w-4 mr-1" />Print / Save PDF
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
