import { useState, useMemo, useEffect } from "react";
import { useNavigate, useSearchParams, useParams } from "react-router";
import { Search, X, Download, ChevronLeft, ChevronRight, RefreshCw, MapPin, Calendar, Clock, FileText, Printer, Ticket, Copy } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Checkbox } from "@/components/ui/checkbox";
import { Skeleton } from "@/components/ui/skeleton";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
// ScrollArea removed (chat tab deleted)
import { Separator } from "@/components/ui/separator";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { useScreenState } from "@/hooks/useScreenState";
import { StateToolbar } from "@/components/StateToolbar";
import { bookings } from "@/mocks/bookings";
import { currentCompany } from "@/mocks/companies";
import { voucherSettings } from "@/mocks/clientManagement";
import CreateTicketDialog from "@/components/CreateTicketDialog";
import { useAuth } from "@/contexts/AuthContext";
import { searchCountries } from "@/lib/countries";
import { downloadCSV, downloadHTML, addExportHistory, getExportHistory, redownloadExport, timestamp, type ExportRecord } from "@/lib/download";
// DateRangePicker replaced with native date inputs for compact DIDA-style filter
// GroupBookingDialog removed — feature intent unclear
import { toast } from "sonner";

const statusColors: Record<string, string> = {
  Confirmed: "default", Cancelled: "destructive",
  "Not Paid": "destructive", "Partially Paid": "secondary", "Fully Paid": "default", Refunded: "secondary", "Partially Refunded": "secondary",
};

/* Export history loaded from localStorage on each open */

function buildInvoiceHTML(bookings: typeof import("@/mocks/bookings").bookings, customer?: { name: string; email: string; phone: string; address: string; regNo: string }): string {
  const today = new Date().toISOString().split("T")[0];
  const cust = customer || { name: "TravelCo International", email: "info@travelco.com", phone: "+82-2-1234-5678", address: "123 Gangnam-daero, Seoul", regNo: "123-45-67890" };
  const invoices = bookings.map(b => {
    const invNo = b.invoiceNo || `INV-${b.ellisCode.slice(-6)}`;
    return `
    <section style="page-break-after: always; padding: 40px; font-family: Arial, sans-serif; max-width: 780px; margin: 0 auto; color: #1a1a2e;">
      <div style="display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 4px solid #FF6000; padding-bottom: 16px; margin-bottom: 24px;">
        <div>
          <div style="color: #FF6000; font-size: 20px; font-weight: bold;">DOTBIZ</div>
          <h1 style="font-size: 36px; letter-spacing: 2px; margin: 8px 0 4px 0;">INVOICE</h1>
          <p style="color: #999; font-size: 11px; margin: 0;">Generated by DOTBIZ Platform</p>
        </div>
        <div style="text-align: right; font-size: 12px;">
          <p style="color: #999; text-transform: uppercase; font-size: 10px; margin: 0;">Invoice No.</p>
          <p style="font-family: monospace; font-weight: bold; font-size: 16px; color: #FF6000; margin: 4px 0 12px 0;">${invNo}</p>
          <p style="margin: 2px 0;"><span style="color: #999;">Issue Date:</span> <strong>${today}</strong></p>
          <p style="margin: 2px 0;"><span style="color: #999;">Booking:</span> <span style="font-family: monospace;">${b.ellisCode}</span></p>
          <p style="margin: 2px 0;"><span style="color: #999;">Status:</span> <strong style="color: ${b.paymentStatus === "Fully Paid" ? "#009505" : "#FF6000"}">${b.paymentStatus}</strong></p>
        </div>
      </div>
      <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 24px;">
        <div style="border: 1px solid #ddd; border-radius: 4px; padding: 12px; background: #f8f8f8;">
          <p style="color: #999; font-size: 10px; text-transform: uppercase; font-weight: bold; margin: 0 0 6px 0;">Supplier</p>
          <p style="font-weight: bold; font-size: 14px; margin: 0;">OhMyHotel Global Pte. Ltd.</p>
          <p style="font-size: 11px; color: #555; margin: 2px 0;">Reg. No. 202543984E · CEO: Lee Misoon</p>
          <p style="font-size: 11px; color: #555; margin: 2px 0;">111 Somerset Road, Singapore 238164</p>
        </div>
        <div style="border: 1px solid #FF6000; border-radius: 4px; padding: 12px; background: #fff4e6;">
          <p style="color: #999; font-size: 10px; text-transform: uppercase; font-weight: bold; margin: 0 0 6px 0;">Customer</p>
          <p style="font-weight: bold; font-size: 14px; margin: 0;">${cust.name}</p>
          <p style="font-size: 11px; color: #555; margin: 2px 0;">Business Reg: ${cust.regNo}</p>
          <p style="font-size: 11px; color: #555; margin: 2px 0;">${cust.address}</p>
          <p style="font-size: 11px; color: #555; margin: 2px 0;">${cust.phone} · ${cust.email}</p>
        </div>
      </div>
      <h3 style="color: #FF6000; font-size: 12px; text-transform: uppercase; margin: 0 0 8px 0;">Booking Item</h3>
      <table style="width: 100%; border-collapse: collapse; font-size: 13px; border: 1px solid #ddd; margin-bottom: 24px;">
        <thead>
          <tr style="background: #f0f0f0; border-bottom: 2px solid #1a1a2e;">
            <th style="padding: 8px; text-align: left; font-size: 10px;">Hotel</th>
            <th style="padding: 8px; text-align: left; font-size: 10px;">Check-in</th>
            <th style="padding: 8px; text-align: center; font-size: 10px;">Nts</th>
            <th style="padding: 8px; text-align: left; font-size: 10px;">Room Type</th>
            <th style="padding: 8px; text-align: left; font-size: 10px;">Guest</th>
            <th style="padding: 8px; text-align: right; font-size: 10px;">Amount</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td style="padding: 8px;">${b.hotelName}</td>
            <td style="padding: 8px;">${b.checkIn}</td>
            <td style="padding: 8px; text-align: center;">${b.nights}</td>
            <td style="padding: 8px;">${b.roomType} × ${b.roomCount}</td>
            <td style="padding: 8px;">${b.traveler}</td>
            <td style="padding: 8px; text-align: right; font-weight: 500;">${b.currency} ${b.sumAmount.toLocaleString()}</td>
          </tr>
        </tbody>
      </table>
      <div style="display: flex; justify-content: flex-end; margin-bottom: 24px;">
        <div style="width: 320px; border: 2px solid #FF6000; border-radius: 4px; overflow: hidden;">
          <div style="background: #1a1a2e; color: white; padding: 10px 14px; font-size: 11px; text-transform: uppercase; font-weight: bold; letter-spacing: 1px;">Summary</div>
          <div style="padding: 14px;">
            <div style="display: flex; justify-content: space-between; align-items: center; font-size: 16px; font-weight: bold;">
              <span>Total Due</span>
              <span style="color: #FF6000; font-size: 20px;">${b.currency} ${b.sumAmount.toLocaleString()}</span>
            </div>
            <p style="font-size: 10px; color: #999; margin: 6px 0 0 0; text-align: right;">* Tax included</p>
          </div>
        </div>
      </div>
      <div style="border: 1px solid #ddd; padding: 12px; background: #f8f8f8; margin-bottom: 16px; font-size: 12px;">
        <p style="color: #FF6000; font-size: 10px; text-transform: uppercase; font-weight: bold; margin: 0 0 6px 0;">Payment Information</p>
        <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px;">
          <div><span style="color: #999; font-size: 10px;">Bank</span><br><strong>DBS Bank Singapore</strong></div>
          <div><span style="color: #999; font-size: 10px;">Account No.</span><br><strong style="font-family: monospace;">012-345678-9</strong></div>
          <div><span style="color: #999; font-size: 10px;">Holder</span><br><strong>OhMyHotel Global Pte. Ltd.</strong></div>
        </div>
      </div>
      <div style="border-left: 4px solid #FF6000; padding: 8px 12px;">
        <p style="color: #FF6000; font-size: 10px; text-transform: uppercase; font-weight: bold; margin: 0 0 4px 0;">Notes</p>
        <p style="font-size: 11px; color: #555; margin: 0;">Please remit the total amount by the due date. Late payments may incur interest charges as per the service agreement.</p>
      </div>
      <div style="margin-top: 24px; padding-top: 12px; border-top: 1px solid #eee; text-align: center; font-size: 9px; color: #999;">
        <p style="margin: 0;">OHMYHOTEL &amp; CO., Ltd. (105-87-71311) · Seoul · Tel: +82-2-762-0552</p>
        <p style="margin: 2px 0 0 0;">© 2026 OHMYHOTEL GLOBAL PTE. LTD. All rights reserved.</p>
      </div>
    </section>`;
  }).join("");
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Invoice</title><style>@page { size: A4; margin: 15mm; } @media print { section { page-break-after: always; } } body { margin: 0; }</style></head><body>${invoices}</body></html>`;
}

interface VoucherOptions {
  showClientLogo?: boolean;   // default true (고객사 로고)
  showOhMyHotelLogo?: boolean; // default false (우리 로고)
  clientName?: string;
  clientPhone?: string;
  clientEmail?: string;
  clientLogoUrl?: string;
}

function buildVoucherHTML(bookings: typeof import("@/mocks/bookings").bookings, options: VoucherOptions = {}): string {
  const { showClientLogo = true, showOhMyHotelLogo = false, clientName = voucherSettings.companyName, clientPhone = voucherSettings.phone, clientEmail = voucherSettings.email, clientLogoUrl = "" } = options;

  const clientHeader = showClientLogo ? `
      <div style="display: flex; align-items: center; gap: 24px; border: 2px solid #FF6000; border-radius: 4px; padding: 16px; margin-bottom: 14px; background: #fff7ed;">
        <div style="display: flex; align-items: center; gap: 10px;">
          ${clientLogoUrl ? `<img src="${clientLogoUrl}" style="width: 56px; height: 56px; object-fit: contain;" alt="Client logo" />` : `<div style="width: 56px; height: 56px; background: #FF6000; border-radius: 8px; display: flex; align-items: center; justify-content: center; color: white; font-weight: bold; font-size: 24px;">${clientName.charAt(0)}</div>`}
          <span style="font-size: 22px; font-weight: bold; color: #1a1a2e;">${clientName}</span>
        </div>
        <div style="font-size: 11px; color: #374151;">
          <p style="margin: 2px 0;">Tel: ${clientPhone}</p>
          <p style="margin: 2px 0;">Email: <span style="color: #2563eb;">${clientEmail}</span></p>
        </div>
      </div>` : "";

  const ohmyHeader = showOhMyHotelLogo ? `
      <div style="display: flex; align-items: center; gap: 24px; border: 1px solid #e2e8f0; border-radius: 4px; padding: 12px; margin-bottom: 20px; background: #f8fafc;">
        <div style="display: flex; align-items: center; gap: 8px;">
          <div style="position: relative; width: 32px; height: 32px;">
            <div style="position: absolute; inset: 0; border-radius: 50%; background: conic-gradient(from 180deg, #FF6000, #FF8C00, #FFCF8F, #FF6000);"></div>
            <div style="position: absolute; inset: 2px; border-radius: 50%; background: white; display: flex; align-items: center; justify-content: center; font-weight: bold; color: #FF6000; font-size: 14px;">O</div>
          </div>
          <span style="font-size: 15px; font-weight: bold; color: #FF6000;">OhMyHotel</span>
        </div>
        <div style="font-size: 10px; color: #6b7280;">
          <p style="margin: 1px 0;">Booking Platform Partner · Tel: +82-2-762-0552</p>
          <p style="margin: 1px 0;">support@ohmyhotel.com</p>
        </div>
      </div>` : "";

  const vouchers = bookings.map(b => {
    const d = new Date(b.checkIn); d.setDate(d.getDate() + b.nights);
    const checkOut = d.toISOString().split("T")[0];
    const ciDay = new Date(b.checkIn).toLocaleDateString("en-US", { weekday: "short" }).toUpperCase();
    const coDay = new Date(checkOut).toLocaleDateString("en-US", { weekday: "short" }).toUpperCase();
    return `
    <section style="page-break-after: always; padding: 40px; font-family: Arial, sans-serif; max-width: 780px; margin: 0 auto; color: #1a1a2e; background: white;">
      ${clientHeader}
      ${ohmyHeader}

      <!-- Voucher Title -->
      <h1 style="color: #FF6000; font-size: 32px; font-weight: bold; margin-bottom: 24px;">Voucher</h1>

      <!-- Booking Information -->
      <h2 style="font-size: 18px; font-weight: bold; border-bottom: 2px solid #FF6000; padding-bottom: 6px; margin-bottom: 16px;">Booking Information</h2>
      <table style="width: 100%; border-collapse: collapse; font-size: 13px; margin-bottom: 28px;">
        <tr style="border-bottom: 1px solid #e5e7eb;"><td style="padding: 10px 0; color: #6b7280; width: 180px; font-weight: 500;">Reference No.</td><td style="padding: 10px 0; color: #1a1a2e; font-weight: 600;">${b.ellisCode} / ${b.hotelConfirmCode || "—"}</td></tr>
        <tr style="border-bottom: 1px solid #e5e7eb;"><td style="padding: 10px 0; color: #6b7280; font-weight: 500;">Booking Code</td><td style="padding: 10px 0; font-family: monospace;">${b.ellisCode}</td></tr>
        <tr style="border-bottom: 1px solid #e5e7eb;"><td style="padding: 10px 0; color: #6b7280; font-weight: 500;">Hotel</td><td style="padding: 10px 0; font-weight: 600;">${b.hotelName}</td></tr>
        <tr style="border-bottom: 1px solid #e5e7eb;"><td style="padding: 10px 0; color: #6b7280; font-weight: 500;">Address</td><td style="padding: 10px 0;">${b.hotelAddress}</td></tr>
        <tr style="border-bottom: 1px solid #e5e7eb;"><td style="padding: 10px 0; color: #6b7280; font-weight: 500;">Tel.</td><td style="padding: 10px 0;">${b.hotelContact}</td></tr>
        <tr style="border-bottom: 1px solid #e5e7eb;"><td style="padding: 10px 0; color: #6b7280; font-weight: 500;">Rooms</td><td style="padding: 10px 0;">${b.roomCount}</td></tr>
        <tr style="border-bottom: 1px solid #e5e7eb;"><td style="padding: 10px 0; color: #6b7280; font-weight: 500;">Check In</td><td style="padding: 10px 0; color: #15803d; font-weight: 600;">${b.checkIn}(${ciDay})</td></tr>
        <tr style="border-bottom: 1px solid #e5e7eb;"><td style="padding: 10px 0; color: #6b7280; font-weight: 500;">Check Out</td><td style="padding: 10px 0; color: #15803d; font-weight: 600;">${checkOut}(${coDay})</td></tr>
        <tr style="border-bottom: 1px solid #e5e7eb;"><td style="padding: 10px 0; color: #6b7280; font-weight: 500;">Room Type</td><td style="padding: 10px 0;">${b.roomType}</td></tr>
        <tr style="border-bottom: 1px solid #e5e7eb;"><td style="padding: 10px 0; color: #6b7280; font-weight: 500;">Meal & Breakfast Type</td><td style="padding: 10px 0;">Room Only</td></tr>
        <tr style="border-bottom: 1px solid #e5e7eb;"><td style="padding: 10px 0; color: #6b7280; font-weight: 500;">Guests</td><td style="padding: 10px 0;"><div style="font-weight: 600;">Room 1</div><div style="color: #374151;">${b.traveler.split(" ").join("/")}</div></td></tr>
        <tr style="border-bottom: 1px solid #e5e7eb;"><td style="padding: 10px 0; color: #6b7280; font-weight: 500;">Guest Requests</td><td style="padding: 10px 0;">${b.specialRequests || "No additional requests"}</td></tr>
      </table>

      <!-- Guidelines -->
      <div style="background: #fff7ed; border: 1px solid #fed7aa; border-radius: 4px; padding: 16px; margin-bottom: 24px;">
        <h3 style="font-size: 13px; font-weight: bold; color: #dc2626; margin: 0 0 8px 0;">[Guidelines]</h3>
        <ul style="list-style: none; padding: 0; margin: 0; font-size: 11px; color: #374151; line-height: 1.6;">
          <li style="margin-bottom: 6px;"><span style="color: #ea580c;">☑</span> Please present the Voucher to the Front desk along with your passport when checking in at the accommodation.</li>
          <li style="margin-bottom: 6px;"><span style="color: #ea580c;">☑</span> Please check your Reservation details before cancelling as Cancellation charge can be applied. In case you do not check in on the check-in date, we will treat this as No-show and your payment will not be refunded. For smooth check-in, please contact the hotel in advance for late check-in after 9pm hotel local time.</li>
          <li style="margin-bottom: 6px;"><span style="color: #ea580c;">☑</span> A room type set for 3 people allows up to 3 people to stay in 1 room, and does not necessarily mean that 3 beds are provided. In some cases, only one double bed or two single beds are provided without an extra bed/mattress, and breakfast can only be provided for two people.</li>
          <li style="margin-bottom: 6px;"><span style="color: #ea580c;">☑</span> Based on the Policies of each hotel, a deposit amount might be required in cash or card. If there is no usage history for the in-room billing service and facilities, the hotel will check and process a refund upon departure.</li>
          <li style="margin-bottom: 6px;"><span style="color: #ea580c;">☑</span> According to local tax regulation in some cities, accommodation tax/city tax/bathing tax, etc. surcharge might be required upon check-in. In addition, additional charges may be incurred due to write-offs/compulsory gala dinners for specific dates. Hotels reserve the right to deny access or apply additional surcharge for unresevred personnel(including infants).</li>
          <li style="margin-bottom: 0;"><span style="color: #ea580c;">☑</span> Membership point/mileage benefits and accumulation operated by the hotel itself are invalid.</li>
        </ul>
      </div>

      <!-- Footer -->
      <div style="border-top: 1px solid #e5e7eb; padding-top: 16px; font-size: 11px; color: #374151;">
        <div style="margin-bottom: 12px;">
          <p style="font-weight: bold; color: #1a1a2e; margin: 0 0 4px 0;">Site Operator</p>
          <p style="margin: 2px 0;">OHMYHOTEL GLOBAL PTE. LTD. (Business Registration No. 202543984E, CEO: LEE MISOON)</p>
          <p style="margin: 2px 0;">111 SOMERSET ROAD, #06-01H, 111 SOMERSET, SINGAPORE 238164</p>
        </div>
        <div>
          <p style="font-weight: bold; color: #1a1a2e; margin: 0 0 4px 0;">Customer Service Center</p>
          <p style="margin: 2px 0;">OHMYHOTEL &amp; CO., Ltd. (Business Registration No. 105-87-71311, CEO: Lee Misoon)</p>
          <p style="margin: 2px 0;">GT Dongdaemun Building 6F, 328 Jongno, Jongno-gu, Seoul, Republic of Korea (Changsin-dong 330-1)</p>
          <p style="margin: 2px 0;">Tel: +82-2-762-0552 (Korea Weekdays 09:00 ~ 18:00, Closed on Weekends &amp; Public Holidays)</p>
          <p style="margin: 2px 0;">E-Commerce Registration No.: 2020-Seoul Jongno-0399 | Privacy Officer: Lee Misoon</p>
        </div>
        <p style="color: #9ca3af; padding-top: 8px; border-top: 1px solid #e5e7eb; margin-top: 8px; font-size: 10px;">© 2026 OHMYHOTEL GLOBAL PTE. LTD. All rights reserved.</p>
      </div>
    </section>`;
  }).join("");
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Hotel Voucher${bookings.length > 1 ? "s" : ""}</title><style>@page { size: A4; margin: 15mm; } @media print { section { page-break-after: always; } } body { margin: 0; background: white; }</style></head><body>${vouchers}</body></html>`;
}

export default function BookingsPage() {
  const { state, setState } = useScreenState("success");
  const { user } = useAuth();
  const billingType = user?.billingType || "POSTPAY";
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { bookingId: routeBookingId } = useParams<{ bookingId: string }>();
  const [localBookings, setLocalBookings] = useState([...bookings]);
  const [selectedBooking, setSelectedBooking] = useState<typeof bookings[0] | null>(null);

  /* When URL is /app/bookings/:bookingId — auto-open the detail dialog */
  useEffect(() => {
    if (routeBookingId) {
      const b = bookings.find(x => x.id === routeBookingId || x.ellisCode === routeBookingId);
      if (b) setSelectedBooking(b);
    }
  }, [routeBookingId]);
  const [cancelOpen, setCancelOpen] = useState(false);
  const [exportHistoryOpen, setExportHistoryOpen] = useState(false);
  const [viewMode, setViewMode] = useState<"list" | "card">("list");
  const [voucherOpen, setVoucherOpen] = useState(false);
  const [voucherShowLogo, setVoucherShowLogo] = useState(false);
  const [voucherShowClientLogo, setVoucherShowClientLogo] = useState(true);
  const [voucherShowQR, setVoucherShowQR] = useState(false);
  const [voucherLang, setVoucherLang] = useState<"EN" | "KO" | "JA" | "ZH" | "VI">("EN");
  const [ticketOpen, setTicketOpen] = useState(false);
  const [ticketBooking, setTicketBooking] = useState<typeof bookings[0] | null>(null);
  const [rowsPerPage, setRowsPerPage] = useState(20);
  const [currentPage, setCurrentPage] = useState(1);
  const [filterDateFrom, setFilterDateFrom] = useState("");
  const [filterDateTo, setFilterDateTo] = useState("");


  /* ── Filters ── */
  const [filterDateType, setFilterDateType] = useState(searchParams.get("dateType") || "Booking");
  const [filterBookingStatus, setFilterBookingStatus] = useState(searchParams.get("status") || "All");

  /* URL param quick filters: free_cancel_24h, free_cancel_3d, upcoming_24h, upcoming_3d */
  const quickFilter = searchParams.get("filter") || "";
  const [filterPaymentStatus, setFilterPaymentStatus] = useState("All");
  const [filterPaymentChannel, setFilterPaymentChannel] = useState("All");
  const [filterEllisCode, setFilterEllisCode] = useState("");
  const [filterHotelConfirm, setFilterHotelConfirm] = useState("");
  const [filterHotelName, setFilterHotelName] = useState("");
  const [filterGuestName, setFilterGuestName] = useState("");
  const [filterGroupId, setFilterGroupId] = useState("");
  const [filterBookerType, setFilterBookerType] = useState("Booker");
  const [filterCountry, setFilterCountry] = useState("");
  const [countryDropdownOpen, setCountryDropdownOpen] = useState(false);
  const [editingSellerCode, setEditingSellerCode] = useState(false);
  const [sellerCodeDraft, setSellerCodeDraft] = useState("");
  const [exportHistoryList, setExportHistoryList] = useState<ExportRecord[]>([]);

  /* Applied filters — only update when Search is clicked */
  const [appliedFilters, setAppliedFilters] = useState({
    bookingStatus: "All", paymentStatus: "All", paymentChannel: "All",
    ellisCode: "", hotelConfirm: "", hotelName: "", guestName: "", groupId: "", country: "", bookerType: "Booker",
    dateType: "Booking Date", dateFrom: "", dateTo: "",
  });
  const applySearch = () => {
    setAppliedFilters({
      bookingStatus: filterBookingStatus, paymentStatus: filterPaymentStatus, paymentChannel: filterPaymentChannel,
      ellisCode: filterEllisCode, hotelConfirm: filterHotelConfirm, hotelName: filterHotelName, guestName: filterGuestName, groupId: filterGroupId,
      country: filterCountry, bookerType: filterBookerType,
      dateType: filterDateType, dateFrom: filterDateFrom, dateTo: filterDateTo,
    });
    toast.success("Search applied");
  };

  /* Batch operations */
  const handleBatchOp = (op: string) => {
    const selected = localBookings.filter(b => selectedIds.has(b.id));
    if (selected.length === 0) { toast.error("No bookings selected"); return; }
    const ts = timestamp();

    if (op === "export_bookings") {
      const rows = selected.map(b => ({
        "Booking Date": b.bookingDate, "ELLIS Code": b.ellisCode, "Hotel Confirmation No.": b.hotelConfirmCode,
        "Booking Status": b.bookingStatus, "Payment Status": b.paymentStatus, "Hotel": b.hotelName,
        "Cancel DL": b.cancelDeadline, "Check-in": b.checkIn, "Nights": b.nights,
        "Room Type": b.roomType, "Rooms": b.roomCount, "Traveler": b.traveler,
        "Currency": b.currency, "Amount": b.sumAmount, "Cancel Date": b.cancelDate,
        "Invoice No.": b.invoiceNo, "Country": b.country, "Pay Channel": b.paymentChannel, "Source": b.bookingSource,
      }));
      const filename = `bookings_${ts}.csv`;
      downloadCSV(filename, rows);
      const csvContent = "\uFEFF" + [Object.keys(rows[0]).join(","), ...rows.map(r => Object.values(r).map(v => { const s = String(v ?? ""); return s.includes(",") ? `"${s}"` : s; }).join(","))].join("\n");
      addExportHistory(filename, rows.length, csvContent);
      toast.success(`Exported ${rows.length} bookings`, { description: filename });
    } else if (op === "export_voucher") {
      /* One voucher file per booking — different customers likely */
      selected.forEach((b, idx) => {
        setTimeout(() => {
          const html = buildVoucherHTML([b]);
          const filename = `voucher_${b.ellisCode}_${ts}.html`;
          downloadHTML(filename, html);
          addExportHistory(filename, 1, html, "text/html;charset=utf-8");
        }, idx * 350);  /* Stagger to avoid browser download blocking */
      });
      toast.success(`Generating ${selected.length} voucher file(s)`, { description: `One file per booking — check your downloads folder` });
    } else if (op === "download_invoice") {
      const withInvoice = selected.filter(b => b.invoiceNo);
      if (withInvoice.length === 0) { toast.error("No invoices found", { description: "Selected bookings have no invoice issued yet." }); return; }
      /* One invoice file per booking */
      withInvoice.forEach((b, idx) => {
        setTimeout(() => {
          const html = buildInvoiceHTML([b], { name: currentCompany.name, email: currentCompany.email, phone: currentCompany.phone, address: currentCompany.address, regNo: currentCompany.businessRegNo });
          const filename = `invoice_${b.invoiceNo || b.ellisCode}_${ts}.html`;
          downloadHTML(filename, html);
          addExportHistory(filename, 1, html, "text/html;charset=utf-8");
        }, idx * 350);
      });
      toast.success(`Generating ${withInvoice.length} invoice file(s)`, { description: `One PDF-ready HTML per booking — open and print to save as PDF` });
    }
  };

  /* ── Batch selection ── */
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const toggleSelect = (id: string) => setSelectedIds(prev => { const n = new Set(prev); n.has(id) ? n.delete(id) : n.add(id); return n; });
  const selectAll = () => { if (selectedIds.size === filtered.length) setSelectedIds(new Set()); else setSelectedIds(new Set(filtered.map(b => b.id))); };

  const resetFilters = () => {
    setFilterDateType("Booking Date"); setFilterBookingStatus("All"); setFilterPaymentStatus("All"); setFilterPaymentChannel("All");
    setFilterEllisCode(""); setFilterHotelConfirm(""); setFilterHotelName(""); setFilterGuestName(""); setFilterGroupId("");
    setFilterCountry(""); setFilterBookerType("Booker");
    setFilterDateFrom(""); setFilterDateTo("");
    setAppliedFilters({ bookingStatus: "All", paymentStatus: "All", paymentChannel: "All", ellisCode: "", hotelConfirm: "", hotelName: "", guestName: "", groupId: "", country: "", bookerType: "Booker", dateType: "Booking Date", dateFrom: "", dateTo: "" });
  };

  /* ── Filtering ── */
  const filtered = useMemo(() => {
    let result = [...localBookings];
    const now = new Date();
    const in24h = new Date(now.getTime() + 24 * 60 * 60 * 1000);
    const in3d = new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000);

    /* Quick filters from URL params */
    if (quickFilter === "free_cancel_24h") {
      result = result.filter(b => b.bookingStatus === "Confirmed" && b.freeCancelDeadline && new Date(b.freeCancelDeadline) <= in24h && new Date(b.freeCancelDeadline) >= now);
    } else if (quickFilter === "free_cancel_3d") {
      result = result.filter(b => b.bookingStatus === "Confirmed" && b.freeCancelDeadline && new Date(b.freeCancelDeadline) <= in3d && new Date(b.freeCancelDeadline) >= now);
    } else if (quickFilter === "upcoming_24h") {
      result = result.filter(b => b.bookingStatus === "Confirmed" && new Date(b.checkIn) <= in24h && new Date(b.checkIn) >= now);
    } else if (quickFilter === "upcoming_3d") {
      result = result.filter(b => b.bookingStatus === "Confirmed" && new Date(b.checkIn) <= in3d && new Date(b.checkIn) >= now);
    } else {
      /* Applied filters — only changes when Search button is clicked */
      /* Date range filter (by selected Date Type) */
      if (appliedFilters.dateFrom || appliedFilters.dateTo) {
        const from = appliedFilters.dateFrom ? new Date(appliedFilters.dateFrom + "T00:00:00") : null;
        const to = appliedFilters.dateTo ? new Date(appliedFilters.dateTo + "T23:59:59") : null;
        result = result.filter(b => {
          /* Pick target date string by dateType */
          let ds = "";
          switch (appliedFilters.dateType) {
            case "Booking Date": ds = b.bookingDate; break;
            case "Cancel Date": ds = b.cancelDate; break;
            case "Check In Date": ds = b.checkIn; break;
            case "Check Out Date": { const d = new Date(b.checkIn + "T00:00:00"); d.setDate(d.getDate() + b.nights); ds = d.toISOString().split("T")[0]; break; }
            case "Cancel Deadline": ds = b.cancelDeadline; break;
            case "Stay Date": {
              /* Stay date: booking overlaps with [from, to] range */
              if (!from && !to) return true;
              const stayStart = new Date(b.checkIn + "T00:00:00");
              const stayEnd = new Date(b.checkIn + "T00:00:00"); stayEnd.setDate(stayEnd.getDate() + b.nights);
              if (from && stayEnd < from) return false;
              if (to && stayStart > to) return false;
              return true;
            }
          }
          if (!ds) return false;
          /* ds might be "YYYY-MM-DD HH:MM(:SS)" or "YYYY-MM-DD" */
          const dsDate = new Date(ds.replace(" ", "T"));
          if (isNaN(dsDate.getTime())) return false;
          if (from && dsDate < from) return false;
          if (to && dsDate > to) return false;
          return true;
        });
      }
      if (appliedFilters.bookingStatus !== "All") result = result.filter(b => b.bookingStatus === appliedFilters.bookingStatus);
      if (appliedFilters.paymentStatus !== "All") result = result.filter(b => b.paymentStatus === appliedFilters.paymentStatus);
      if (appliedFilters.paymentChannel !== "All") result = result.filter(b => b.paymentChannel === appliedFilters.paymentChannel);
      if (appliedFilters.ellisCode) result = result.filter(b => b.ellisCode.toLowerCase().includes(appliedFilters.ellisCode.toLowerCase()));
      if (appliedFilters.hotelConfirm) result = result.filter(b => b.hotelConfirmCode.toLowerCase().includes(appliedFilters.hotelConfirm.toLowerCase()));
      if (appliedFilters.hotelName) result = result.filter(b => b.hotelName.toLowerCase().includes(appliedFilters.hotelName.toLowerCase()));
      if (appliedFilters.guestName) {
        const q = appliedFilters.guestName.toLowerCase();
        if (appliedFilters.bookerType === "Traveler") result = result.filter(b => b.traveler.toLowerCase().includes(q));
        else if (appliedFilters.bookerType === "Mobile No.") result = result.filter(b => b.guestMobile.toLowerCase().includes(q));
        else result = result.filter(b => b.guestName.toLowerCase().includes(q));
      }
      if (appliedFilters.country) result = result.filter(b => b.country.toLowerCase().includes(appliedFilters.country.toLowerCase()));
      if (appliedFilters.groupId) result = result.filter(b => b.groupBookingId.toLowerCase().includes(appliedFilters.groupId.toLowerCase()));
    }
    return result;
  }, [localBookings, quickFilter, appliedFilters]);

  const totalPages = Math.max(1, Math.ceil(filtered.length / rowsPerPage));
  const paginated = filtered.slice((currentPage - 1) * rowsPerPage, currentPage * rowsPerPage);

  // Reset page when filters change
  useEffect(() => { setCurrentPage(1); }, [filtered.length, rowsPerPage]);

  if (state === "loading") return (<div className="p-6 space-y-4"><Skeleton className="h-10 w-96" /><Skeleton className="h-24 w-full" /><Skeleton className="h-96 w-full" /><StateToolbar state={state} setState={setState} /></div>);
  if (state === "empty") return (<div className="p-6"><Card className="max-w-md mx-auto mt-20 p-6 text-center"><h2 className="text-xl font-semibold">No Bookings Yet</h2><p className="text-muted-foreground mt-2">Start searching for hotels to create your first booking.</p><Button className="mt-4" onClick={() => navigate("/app/find-hotel")}><Search className="h-4 w-4 mr-2" />Find Hotel</Button></Card><StateToolbar state={state} setState={setState} /></div>);
  if (state === "error") return (<div className="p-6"><Alert variant="destructive" className="max-w-md mx-auto"><AlertTitle>Bookings Error</AlertTitle><AlertDescription>Failed to load bookings. Please try again.</AlertDescription><Button className="mt-3" onClick={() => setState("success")}><RefreshCw className="h-4 w-4 mr-2" />Retry</Button></Alert><StateToolbar state={state} setState={setState} /></div>);

  return (
    <div className="p-6 space-y-4">
      <div className="flex items-center gap-3">
        <h1 className="text-2xl font-bold">Bookings</h1>
        {quickFilter && (
          <Badge style={{ background: quickFilter.startsWith("free") ? "#009505" : "#FF6000" }} className="text-xs text-white">
            {quickFilter === "free_cancel_24h" && "Free Cancel — Within 24h"}
            {quickFilter === "free_cancel_3d" && "Free Cancel — Within 3 days"}
            {quickFilter === "upcoming_24h" && "Upcoming — Within 24h"}
            {quickFilter === "upcoming_3d" && "Upcoming — Within 3 days"}
            <button className="ml-2 hover:opacity-70" onClick={() => navigate("/app/bookings")}>✕</button>
          </Badge>
        )}
      </div>

      <Tabs defaultValue="list">
        <TabsList>
          <TabsTrigger value="list">Booking List</TabsTrigger>
        </TabsList>

        <TabsContent value="list" className="space-y-4 mt-4">
          {/* ── Filters (DIDA style) ── */}
          <Card className="p-4 overflow-visible">
            {/* Row 1: Date + ELLIS Code + Status + Search/Reset */}
            <div className="flex items-center gap-3 flex-wrap mb-3">
              <div className="flex items-center gap-2">
                <select value={filterDateType} onChange={e => setFilterDateType(e.target.value)} className="border rounded px-2 py-1.5 text-xs bg-background h-8" aria-label="Date type">
                  {["Booking Date", "Cancel Date", "Check In Date", "Check Out Date", "Cancel Deadline", "Stay Date"].map(o => <option key={o}>{o}</option>)}
                </select>
                <Input type="date" value={filterDateFrom} onChange={e => setFilterDateFrom(e.target.value)} className="text-xs h-8 w-36" />
                <span className="text-xs text-muted-foreground">→</span>
                <Input type="date" value={filterDateTo} onChange={e => setFilterDateTo(e.target.value)} className="text-xs h-8 w-36" />
              </div>
              <div className="flex items-center gap-1.5">
                <label className="text-xs text-muted-foreground">ELLIS BKG Code</label>
                <Input placeholder="K26..." value={filterEllisCode} onChange={e => setFilterEllisCode(e.target.value)} className="text-xs h-8 w-40" />
              </div>
              <div className="flex items-center gap-1.5">
                <label className="text-xs text-muted-foreground">BKG Status</label>
                <select value={filterBookingStatus} onChange={e => setFilterBookingStatus(e.target.value)} className="border rounded px-2 py-1.5 text-xs bg-background h-8" aria-label="Booking status">
                  {["All", "Confirmed", "Cancelled"].map(o => <option key={o}>{o}</option>)}
                </select>
              </div>
              <div className="flex items-center gap-2 ml-auto">
                <Button size="sm" className="h-8" onClick={applySearch} style={{ background: "#FF6000" }}><Search className="h-3.5 w-3.5 mr-1" />Search</Button>
                <Button size="sm" variant="outline" className="h-8" onClick={resetFilters}>Reset</Button>
              </div>
            </div>
            {/* Row 2: Payment + Booker (type+name) + Country + Hotel Name */}
            <div className="flex items-center gap-3 flex-wrap mb-3">
              <div className="flex items-center gap-1.5">
                <label className="text-xs text-muted-foreground">Payment Status</label>
                <select value={filterPaymentStatus} onChange={e => setFilterPaymentStatus(e.target.value)} className="border rounded px-2 py-1.5 text-xs bg-background h-8" aria-label="Payment status">
                  {["All", "Not Paid", "Partially Paid", "Fully Paid", "Refunded", "Partially Refunded"].map(o => <option key={o}>{o}</option>)}
                </select>
              </div>
              <div className="flex items-center gap-2">
                <select value={filterBookerType} onChange={e => setFilterBookerType(e.target.value)} className="border rounded px-2 py-1.5 text-xs bg-background h-8" aria-label="Booker search type">
                  {["Booker", "Traveler", "Mobile No."].map(o => <option key={o}>{o}</option>)}
                </select>
                <Input placeholder={filterBookerType === "Mobile No." ? "+82..." : "Name"} value={filterGuestName} onChange={e => setFilterGuestName(e.target.value)} className="text-xs h-8 w-36" />
              </div>
              <div className="flex items-center gap-1.5 relative">
                <label className="text-xs text-muted-foreground">Country</label>
                <div className="relative">
                  <Input
                    placeholder="ko, KR, Korea..."
                    value={filterCountry}
                    onChange={e => { setFilterCountry(e.target.value); setCountryDropdownOpen(true); }}
                    onFocus={() => setCountryDropdownOpen(true)}
                    onBlur={() => setTimeout(() => setCountryDropdownOpen(false), 200)}
                    className="text-xs h-8 w-40"
                  />
                  {countryDropdownOpen && filterCountry && searchCountries(filterCountry).length > 0 && (
                    <div className="absolute top-full left-0 mt-1 w-56 bg-card border rounded-md shadow-lg z-20 max-h-60 overflow-y-auto">
                      {searchCountries(filterCountry).map(c => (
                        <button
                          key={c.code}
                          onMouseDown={(e) => { e.preventDefault(); setFilterCountry(c.name); setCountryDropdownOpen(false); }}
                          className="w-full text-left px-3 py-1.5 text-xs hover:bg-accent flex items-center gap-2"
                        >
                          <span className="font-mono text-muted-foreground w-8">{c.code}</span>
                          <span>—</span>
                          <span>{c.name}</span>
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              </div>
              <div className="flex items-center gap-1.5">
                <label className="text-xs text-muted-foreground">Hotel Name</label>
                <Input placeholder="" value={filterHotelName} onChange={e => setFilterHotelName(e.target.value)} className="text-xs h-8 w-44" />
              </div>
            </div>
            {/* Row 3: Hotel Confirmation No. */}
            <div className="flex items-center gap-3">
              <div className="flex items-center gap-1.5">
                <label className="text-xs text-muted-foreground">Hotel Confirm No.</label>
                <Input placeholder="" value={filterHotelConfirm} onChange={e => setFilterHotelConfirm(e.target.value)} className="text-xs h-8 w-40" />
              </div>
            </div>
          </Card>

          {/* ── Batch Action Bar ── */}
          {selectedIds.size > 0 && (
            <div className="flex items-center gap-3 p-3 bg-primary/5 border border-primary/20 rounded-lg">
              <span className="text-sm font-medium">{selectedIds.size} booking{selectedIds.size > 1 ? "s" : ""} selected</span>
              <Separator orientation="vertical" className="h-5" />
              <select className="border rounded px-3 py-1.5 text-xs bg-background" style={{ borderColor: "#FF6000", color: "#FF6000" }} value="" onChange={e => { const v = e.target.value; if (v) handleBatchOp(v); e.target.value = ""; }} aria-label="Batch operation">
                <option value="" disabled>Batch Operation</option>
                <option value="export_bookings">Export Hotel Bookings (CSV)</option>
                <option value="export_voucher">Export Booking Voucher (PDF)</option>
                <option value="download_invoice">Download Invoice (PDF)</option>
              </select>
              <Button size="sm" variant="outline" onClick={() => { setExportHistoryList(getExportHistory()); setExportHistoryOpen(true); }}><FileText className="h-3 w-3 mr-1" />Export History</Button>
              <Button size="sm" variant="ghost" className="ml-auto" onClick={() => setSelectedIds(new Set())}>Clear Selection</Button>
            </div>
          )}

          {/* ── Toolbar + Pagination ── */}
          <div className="flex items-center justify-between">
            <span className="text-sm" style={{ color: "#FF6000" }}>{filtered.length}</span>
            <div className="flex items-center gap-2">
              <Button variant="outline" size="sm" onClick={() => {
                const rows = filtered.map(b => ({
                  "Booking Date": b.bookingDate, "ELLIS Code": b.ellisCode, "Hotel Confirmation No.": b.hotelConfirmCode,
                  "Booking Status": b.bookingStatus, "Payment Status": b.paymentStatus, "Hotel": b.hotelName,
                  "Cancel DL": b.cancelDeadline, "Check-in": b.checkIn, "Nights": b.nights,
                  "Room Type": b.roomType, "Rooms": b.roomCount, "Traveler": b.traveler,
                  "Currency": b.currency, "Amount": b.sumAmount, "Cancel Date": b.cancelDate,
                  "Invoice No.": b.invoiceNo, "Country": b.country, "Pay Channel": b.paymentChannel, "Source": b.bookingSource,
                }));
                if (rows.length === 0) { toast.error("No bookings to export"); return; }
                const filename = `bookings_all_${timestamp()}.csv`;
                downloadCSV(filename, rows);
                const csvContent = "\uFEFF" + [Object.keys(rows[0]).join(","), ...rows.map(r => Object.values(r).map(v => { const s = String(v ?? ""); return s.includes(",") ? `"${s}"` : s; }).join(","))].join("\n");
                addExportHistory(filename, rows.length, csvContent);
                toast.success(`Exported ${rows.length} bookings`, { description: filename });
              }}><Download className="h-3 w-3 mr-1" />Excel</Button>
              <select className="text-xs border rounded px-2 py-1 bg-background" value={rowsPerPage} onChange={e => setRowsPerPage(Number(e.target.value))} aria-label="Rows per page">
                {[20, 40, 60, 80, 100].map(n => <option key={n} value={n}>{n}</option>)}
              </select>
            </div>
          </div>

          {/* ── List View ──
           * 컬럼은 일일 운영에 필수적인 8개로 축소. 나머지 상세 정보(Hotel Confirm No,
           * Payment Status, Cancel DL, Currency, Invoice No, Pay Channel, Booking Source,
           * Dispute 등)는 ELLIS Code 클릭 시 열리는 상세 다이얼로그에 표시. */}
          {viewMode === "list" ? (
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow className="text-[11px]">
                    <TableHead className="w-8"><Checkbox checked={selectedIds.size === filtered.length && filtered.length > 0} onCheckedChange={selectAll} /></TableHead>
                    <TableHead className="whitespace-nowrap">Booking Date</TableHead>
                    <TableHead className="whitespace-nowrap">ELLIS Code</TableHead>
                    <TableHead className="whitespace-nowrap">Status</TableHead>
                    <TableHead>Hotel</TableHead>
                    <TableHead className="whitespace-nowrap">Check-in / Nts</TableHead>
                    <TableHead>Traveler</TableHead>
                    <TableHead className="whitespace-nowrap text-right">Amount</TableHead>
                    <TableHead className="whitespace-nowrap text-center">Action</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {paginated.map(b => (
                    <TableRow key={b.id} className="group hover:bg-muted/50 text-xs cursor-pointer" onClick={() => setSelectedBooking(b)}>
                      <TableCell onClick={e => e.stopPropagation()}><Checkbox checked={selectedIds.has(b.id)} onCheckedChange={() => toggleSelect(b.id)} /></TableCell>
                      <TableCell className="whitespace-nowrap">{b.bookingDate}</TableCell>
                      <TableCell className="whitespace-nowrap" onClick={e => e.stopPropagation()}>
                        <span className="font-mono text-[#0066cc] hover:underline cursor-pointer" onClick={() => setSelectedBooking(b)}>{b.ellisCode}</span>
                        <button className="ml-1 text-muted-foreground hover:text-foreground opacity-0 group-hover:opacity-100" title="Copy booking code" onClick={(e) => { e.stopPropagation(); navigator.clipboard.writeText(b.ellisCode); toast.success("Copied!", { description: b.ellisCode }); }}>
                          <Copy className="h-3 w-3 inline" />
                        </button>
                      </TableCell>
                      <TableCell>
                        {/* Booking + Payment 둘 다 한 셀에 — 좁게 표시 */}
                        <div className="flex flex-col gap-0.5">
                          <Badge variant={statusColors[b.bookingStatus] as "default" | "destructive" | "secondary"} className="text-[10px] w-fit">{b.bookingStatus}</Badge>
                          <span className="text-[9px] text-muted-foreground">{b.paymentStatus}</span>
                        </div>
                      </TableCell>
                      <TableCell className="truncate max-w-[200px]">{b.hotelName}</TableCell>
                      <TableCell className="whitespace-nowrap">{b.checkIn} <span className="text-muted-foreground">[{b.nights}N]</span></TableCell>
                      <TableCell className="truncate max-w-[140px]">{b.traveler}</TableCell>
                      <TableCell className="text-right font-medium whitespace-nowrap">
                        <span className="text-[10px] text-muted-foreground mr-1">{b.currency}</span>
                        {b.sumAmount.toLocaleString()}
                      </TableCell>
                      <TableCell className="text-center" onClick={e => e.stopPropagation()}>
                        <Button variant="ghost" size="sm" className="h-6 px-2 text-[10px] text-[#FF6000] hover:bg-[#FF6000]/10" onClick={(e) => { e.stopPropagation(); setTicketBooking(b); setTicketOpen(true); }} title="Create ticket for this booking">
                          <Ticket className="h-3 w-3 mr-1" />Ticket
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          ) : (
            /* ── Card View ── */
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {paginated.map(b => (
                <Card key={b.id} className="p-4 cursor-pointer card-hover" onClick={() => setSelectedBooking(b)}>
                  <div className="flex items-start justify-between mb-2">
                    <div>
                      <h3 className="font-bold text-sm">{b.hotelName}</h3>
                      <p className="text-xs text-muted-foreground flex items-center gap-1 mt-0.5"><MapPin className="h-3 w-3" />{b.hotelAddress.split(",").slice(-1)[0].trim()}</p>
                    </div>
                    <div className="flex gap-1">
                      <Badge variant={statusColors[b.bookingStatus] as "default" | "destructive" | "secondary"} className="text-[10px]">{b.bookingStatus}</Badge>
                      <Badge variant={statusColors[b.paymentStatus] as "default" | "destructive" | "secondary"} className="text-[10px]">{b.paymentStatus}</Badge>
                    </div>
                  </div>
                  <Separator className="my-2" />
                  <div className="grid grid-cols-2 gap-2 text-xs">
                    <div className="flex items-center gap-1.5"><Calendar className="h-3 w-3 text-muted-foreground" /><span>{b.checkIn} ({b.nights}N)</span></div>
                    <div className="flex items-center gap-1.5"><Clock className="h-3 w-3 text-muted-foreground" /><span>Cancel by {b.freeCancelDeadline}</span></div>
                    <div><span className="text-muted-foreground">Room:</span> {b.roomType} x{b.roomCount}</div>
                    <div><span className="text-muted-foreground">Guest:</span> {b.traveler}</div>
                  </div>
                  <div className="flex items-center justify-between mt-3 pt-2 border-t">
                    <div className="text-xs">
                      <span className="font-mono text-muted-foreground">{b.ellisCode}</span>
                      {b.groupBookingId && <Badge variant="outline" className="text-[9px] ml-2">{b.groupBookingId}</Badge>}
                    </div>
                    <span className="text-sm font-bold" style={{ color: "#FF6000" }}>${b.sumAmount.toLocaleString()}</span>
                  </div>
                </Card>
              ))}
            </div>
          )}

          {/* ── Pagination (DIDA style, always visible) ── */}
          {filtered.length > 0 && (
            <div className="flex items-center justify-between pt-3 pb-2 border-t mt-3 px-2">
              <div className="flex items-center gap-0.5">
                <Button variant="ghost" size="sm" className="h-8 w-8 p-0 text-muted-foreground hover:text-foreground" disabled={currentPage === 1} onClick={() => setCurrentPage(1)} aria-label="First page">
                  <span className="flex"><ChevronLeft className="h-3.5 w-3.5" /><ChevronLeft className="h-3.5 w-3.5 -ml-2.5" /></span>
                </Button>
                <Button variant="ghost" size="sm" className="h-8 w-8 p-0 text-muted-foreground hover:text-foreground" disabled={currentPage === 1} onClick={() => setCurrentPage(p => p - 1)} aria-label="Previous page">
                  <ChevronLeft className="h-4 w-4" />
                </Button>
                {Array.from({ length: Math.min(5, totalPages) }, (_, i) => {
                  let page: number;
                  if (totalPages <= 5) page = i + 1;
                  else if (currentPage <= 3) page = i + 1;
                  else if (currentPage >= totalPages - 2) page = totalPages - 4 + i;
                  else page = currentPage - 2 + i;
                  const isActive = page === currentPage;
                  return (
                    <button
                      key={page}
                      onClick={() => setCurrentPage(page)}
                      className={`h-8 min-w-[32px] px-2 text-xs rounded transition-colors ${isActive ? "bg-orange-100 text-[#FF6000] font-semibold dark:bg-orange-900/30" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`}
                    >
                      {page}
                    </button>
                  );
                })}
                <Button variant="ghost" size="sm" className="h-8 w-8 p-0 text-muted-foreground hover:text-foreground" disabled={currentPage === totalPages} onClick={() => setCurrentPage(p => p + 1)} aria-label="Next page">
                  <ChevronRight className="h-4 w-4" />
                </Button>
                <Button variant="ghost" size="sm" className="h-8 w-8 p-0 text-muted-foreground hover:text-foreground" disabled={currentPage === totalPages} onClick={() => setCurrentPage(totalPages)} aria-label="Last page">
                  <span className="flex"><ChevronRight className="h-3.5 w-3.5" /><ChevronRight className="h-3.5 w-3.5 -ml-2.5" /></span>
                </Button>
              </div>
              <p className="text-xs text-muted-foreground">
                {(currentPage - 1) * rowsPerPage + 1} - {Math.min(currentPage * rowsPerPage, filtered.length)} of {filtered.length} items
              </p>
            </div>
          )}
        </TabsContent>

      </Tabs>

      {/* ── Booking Detail Modal (DIDA style) ── */}
      <Dialog open={!!selectedBooking} onOpenChange={() => setSelectedBooking(null)}>
        <DialogContent className="max-h-[90vh] overflow-y-auto p-0" style={{ maxWidth: "1200px", width: "90vw" }}>
          {/* Dark header */}
          <div className="px-5 py-3" style={{ background: "linear-gradient(90deg, #1a1a2e, #16213e)" }}>
            <DialogHeader><DialogTitle className="text-white text-sm font-mono">{selectedBooking?.ellisCode}</DialogTitle></DialogHeader>
          </div>
          {selectedBooking && (
            <div className="p-5 space-y-4">
              {/* OMH Reservation number */}
              <p className="text-sm font-semibold border-b pb-2">OMH Reservation number : <span className="font-mono">{selectedBooking.ellisCode}</span></p>

              {/* Booker */}
              <Card className="p-4">
                <div className="flex items-center justify-between mb-3">
                  <h3 className="font-bold text-sm">Booker</h3>
                </div>
                <Table>
                  <TableBody>
                    <TableRow><TableCell className="text-sm font-medium w-36">Name</TableCell><TableCell className="text-sm">{selectedBooking.guestName}</TableCell></TableRow>
                    <TableRow><TableCell className="text-sm font-medium">Email</TableCell><TableCell className="text-sm text-primary">{selectedBooking.guestEmail}</TableCell></TableRow>
                    <TableRow><TableCell className="text-sm font-medium">Tel</TableCell><TableCell className="text-sm">{selectedBooking.guestMobile}</TableCell></TableRow>
                    <TableRow>
                      <TableCell className="text-sm font-medium">Hotel Confirmation No.</TableCell>
                      <TableCell className="text-sm">
                        {editingSellerCode ? (
                          <div className="flex items-center gap-2">
                            <Input value={sellerCodeDraft} onChange={e => setSellerCodeDraft(e.target.value)} className="h-7 text-xs max-w-[220px]" placeholder="Enter hotel confirmation no" autoFocus />
                            <Button size="sm" className="h-7 text-xs" style={{ background: "#FF6000" }} onClick={() => { setLocalBookings(prev => prev.map(b => b.id === selectedBooking.id ? { ...b, hotelConfirmCode: sellerCodeDraft.trim() } : b)); toast.success("Hotel Confirmation No. saved"); setEditingSellerCode(false); }}>Save</Button>
                            <Button size="sm" variant="outline" className="h-7 text-xs" onClick={() => setEditingSellerCode(false)}>Cancel</Button>
                          </div>
                        ) : (
                          <div className="flex items-center gap-2">
                            <span>{selectedBooking.hotelConfirmCode || <span className="text-muted-foreground italic">(Not set)</span>}</span>
                            <button className="text-xs text-[#0066cc] hover:underline" onClick={() => { setSellerCodeDraft(selectedBooking.hotelConfirmCode || ""); setEditingSellerCode(true); }}>
                              ✎ {selectedBooking.hotelConfirmCode ? "Edit" : "Add"}
                            </button>
                          </div>
                        )}
                      </TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </Card>

              {/* Reservation Details */}
              <Card className="p-4">
                <div className="flex items-center justify-between mb-3">
                  <h3 className="font-bold text-sm">Reservation Details</h3>
                  <div className="flex gap-2">
                    {selectedBooking.bookingStatus !== "Cancelled" && (
                      <Button variant="outline" size="sm" className="h-7 text-xs border-red-300 text-red-500 hover:bg-red-50" onClick={() => {
                        if (new Date(selectedBooking.cancelDeadline) > new Date()) {
                          setCancelOpen(true);
                        } else {
                          toast.error("Cancellation deadline has passed.", { description: `Deadline was ${selectedBooking.cancelDeadline}. Full charge will be applied.` });
                        }
                      }}>Cancel</Button>
                    )}
                    <Button variant="outline" size="sm" className="h-7 text-xs" onClick={() => setVoucherOpen(true)}>Voucher</Button>
                    <Button variant="outline" size="sm" className="h-7 text-xs" onClick={() => {
                      const b = selectedBooking;
                      const invNo = b.invoiceNo || `INV-PREVIEW-${b.ellisCode.slice(-6)}`;
                      const html = buildInvoiceHTML([b], { name: currentCompany.name, email: currentCompany.email, phone: currentCompany.phone, address: currentCompany.address, regNo: currentCompany.businessRegNo });
                      const filename = `invoice_${invNo}_${timestamp()}.html`;
                      downloadHTML(filename, html);
                      addExportHistory(filename, 1, html, "text/html;charset=utf-8");
                      toast.success(`Invoice ${invNo} downloaded`, { description: `${filename} — open and print to save as PDF` });
                    }}><Download className="h-3 w-3 mr-1" />Invoice</Button>
                  </div>
                </div>
                <Table>
                  <TableBody>
                    <TableRow><TableCell className="text-sm font-medium w-48">Booking Status / Payment Status</TableCell><TableCell className="text-sm font-bold">{selectedBooking.bookingStatus} / {selectedBooking.paymentStatus}</TableCell></TableRow>
                    <TableRow><TableCell className="text-sm font-medium">Check in / Out Date</TableCell><TableCell className="text-sm">{selectedBooking.checkIn} ~ {(() => { const d = new Date(selectedBooking.checkIn); d.setDate(d.getDate() + selectedBooking.nights); return d.toISOString().split("T")[0]; })()} [{selectedBooking.nights}NTS]</TableCell></TableRow>
                    <TableRow><TableCell className="text-sm font-medium">Region name</TableCell><TableCell className="text-sm">{selectedBooking.hotelAddress.split(",").pop()?.trim()}</TableCell></TableRow>
                    <TableRow><TableCell className="text-sm font-medium">Hotel Name</TableCell><TableCell className="text-sm">{selectedBooking.hotelName}</TableCell></TableRow>
                    <TableRow><TableCell className="text-sm font-medium">Rooms / Travelers</TableCell><TableCell className="text-sm text-primary">{selectedBooking.roomCount} Rooms / 2 Travelers</TableCell></TableRow>
                    <TableRow><TableCell className="text-sm font-medium">Room Type</TableCell><TableCell className="text-sm">{selectedBooking.roomType}</TableCell></TableRow>
                    <TableRow><TableCell className="text-sm font-medium">Meal Type</TableCell><TableCell className="text-sm">None</TableCell></TableRow>
                    <TableRow><TableCell className="text-sm font-medium">Cancellation D/L</TableCell><TableCell className={`text-sm font-medium ${new Date(selectedBooking.cancelDeadline) > new Date() ? "text-[#FF6000]" : "text-red-500"}`}>{selectedBooking.cancelDeadline}</TableCell></TableRow>
                    {selectedBooking.cancelDate && (
                      <TableRow><TableCell className="text-sm font-medium">Cancelled Date</TableCell><TableCell className="text-sm text-red-500">{selectedBooking.cancelDate}</TableCell></TableRow>
                    )}
                    <TableRow>
                      <TableCell className="text-sm font-medium">Booking Source</TableCell>
                      <TableCell className="text-sm">
                        <Badge variant="outline" className={`text-[10px] ${selectedBooking.bookingSource === "API Integration" ? "border-purple-300 text-purple-600" : "border-orange-300 text-[#FF6000]"}`}>{selectedBooking.bookingSource}</Badge>
                      </TableCell>
                    </TableRow>
                    {selectedBooking.dispute && (
                      <TableRow><TableCell className="text-sm font-medium text-red-500">Dispute</TableCell><TableCell className="text-sm text-red-500">{selectedBooking.dispute}</TableCell></TableRow>
                    )}
                  </TableBody>
                </Table>
              </Card>

              {/* Travelers */}
              <Card className="p-4">
                <h3 className="font-bold text-sm mb-3">Travelers</h3>
                <Table>
                  <TableHeader>
                    <TableRow className="text-xs">
                      <TableHead>Rooms</TableHead><TableHead>Gender</TableHead><TableHead>Name(Local Language)</TableHead><TableHead>Last Name / First Name (EN)</TableHead><TableHead>Child Birthday</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell className="text-xs">Rooms 1</TableCell><TableCell className="text-xs">M</TableCell><TableCell className="text-xs">—</TableCell><TableCell className="text-xs font-medium">{selectedBooking.traveler.split(" ").map(n => n.toUpperCase()).join(" / ")}</TableCell><TableCell className="text-xs">—</TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </Card>

              {/* Special Request */}
              <Card className="p-4">
                <h3 className="font-bold text-sm mb-3">Special Request</h3>
                <p className="text-sm text-muted-foreground">{selectedBooking.specialRequests || "No special requests"}</p>
              </Card>

              {/* Billing & Payment */}
              <Card className="p-4">
                <div className="flex items-center justify-between mb-3">
                  <h3 className="font-bold text-sm">Billing & Payment</h3>
                  <div className="flex items-center gap-2">
                    <Badge variant={billingType === "PREPAY" ? "destructive" : "default"} className="text-[10px]">{billingType}</Badge>
                    <Badge variant="outline" className="text-xs">{selectedBooking.paymentChannel}</Badge>
                  </div>
                </div>
                <Table>
                  <TableBody>
                    <TableRow><TableCell className="text-sm font-medium w-48">Billing total</TableCell><TableCell className="text-sm text-right font-medium">{selectedBooking.currency} {selectedBooking.sumAmount.toLocaleString()}</TableCell></TableRow>
                    <TableRow>
                      <TableCell className="text-sm font-medium">Payment Status</TableCell>
                      <TableCell className="text-sm text-right">
                        <Badge variant={statusColors[selectedBooking.paymentStatus] as "default" | "destructive" | "secondary"} className="text-[10px]">{selectedBooking.paymentStatus}</Badge>
                      </TableCell>
                    </TableRow>
                    <TableRow><TableCell className="text-sm font-medium">Balance</TableCell><TableCell className="text-sm text-right font-medium">{selectedBooking.currency} {selectedBooking.paymentStatus === "Fully Paid" || selectedBooking.paymentStatus === "Refunded" ? "0" : selectedBooking.sumAmount.toLocaleString()}</TableCell></TableRow>
                    {selectedBooking.invoiceNo && (
                      <TableRow><TableCell className="text-sm font-medium">Invoice No.</TableCell><TableCell className="text-sm text-right font-mono">{selectedBooking.invoiceNo}</TableCell></TableRow>
                    )}
                  </TableBody>
                </Table>
                {/* Billing flow explanation */}
                <div className="mt-3 p-3 rounded bg-muted/40 border text-xs text-muted-foreground">
                  {billingType === "POSTPAY" ? (
                    <>
                      <p className="font-medium text-foreground mb-1">📋 POSTPAY flow</p>
                      <p><strong>Not Paid</strong> (booking created) → <strong>Invoice issued</strong> (by settlement cycle) → Client wire transfer → <strong>Fully Paid</strong> (confirmed by accounting team).</p>
                    </>
                  ) : (
                    <>
                      <p className="font-medium text-foreground mb-1">💳 PREPAY flow</p>
                      <p><strong>Not Paid</strong> → PG card payment at booking → <strong>Fully Paid</strong> (instant). Refunds trigger <strong>Refunded</strong> / <strong>Partially Refunded</strong>.</p>
                    </>
                  )}
                </div>
                {/* POSTPAY Issue Invoice action */}
                {billingType === "POSTPAY" && !selectedBooking.invoiceNo && selectedBooking.paymentStatus === "Not Paid" && (
                  <div className="mt-3 flex justify-end">
                    <Button size="sm" variant="outline" className="h-8 text-xs border-[#FF6000] text-[#FF6000]" onClick={() => {
                      const invNo = `INV-2026-${String(Math.floor(Math.random() * 9000) + 1000)}`;
                      setLocalBookings(prev => prev.map(b => b.id === selectedBooking.id ? { ...b, invoiceNo: invNo } : b));
                      toast.success(`Invoice ${invNo} issued`, { description: "Awaiting client payment" });
                    }}>📄 Issue Invoice</Button>
                  </div>
                )}
                {/* Accounting team: mark as paid */}
                {billingType === "POSTPAY" && selectedBooking.invoiceNo && selectedBooking.paymentStatus === "Not Paid" && user?.role === "Master" && (
                  <div className="mt-3 flex justify-end gap-2">
                    <Button size="sm" variant="outline" className="h-8 text-xs" onClick={() => {
                      setLocalBookings(prev => prev.map(b => b.id === selectedBooking.id ? { ...b, paymentStatus: "Partially Paid" as const } : b));
                      toast.success("Marked as Partially Paid");
                    }}>Mark Partially Paid</Button>
                    <Button size="sm" className="h-8 text-xs" style={{ background: "#009505" }} onClick={() => {
                      setLocalBookings(prev => prev.map(b => b.id === selectedBooking.id ? { ...b, paymentStatus: "Fully Paid" as const } : b));
                      toast.success("Marked as Fully Paid", { description: "Payment confirmed by accounting" });
                    }}>✓ Mark Fully Paid</Button>
                  </div>
                )}
              </Card>

              {/* Cancellation Policy (DIDA table style) */}
              <Card className="p-4">
                <h3 className="font-bold text-sm mb-3">Cancellation Policy</h3>
                <Table>
                  <TableHeader>
                    <TableRow className="text-xs">
                      <TableHead>Your Local Time</TableHead>
                      <TableHead>Property's local time</TableHead>
                      <TableHead>Days Left</TableHead>
                      <TableHead>Fee</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell className="text-xs text-green-600">Before {selectedBooking.cancelDeadline}</TableCell>
                      <TableCell className="text-xs text-green-600">Before {selectedBooking.cancelDeadline}</TableCell>
                      <TableCell className="text-xs text-primary">{Math.max(0, Math.ceil((new Date(selectedBooking.cancelDeadline).getTime() - Date.now()) / 86400000))} days</TableCell>
                      <TableCell className="text-xs text-green-600 font-medium">Refundable</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="text-xs">From {selectedBooking.cancelDeadline}</TableCell>
                      <TableCell className="text-xs">From {selectedBooking.cancelDeadline}</TableCell>
                      <TableCell className="text-xs">{Math.max(0, Math.ceil((new Date(selectedBooking.cancelDeadline).getTime() - Date.now()) / 86400000))} days</TableCell>
                      <TableCell className="text-xs text-red-500 font-medium">Non-Refundable</TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </Card>

              {/* Bottom Actions (DIDA style) */}
              <div className="flex items-center justify-between pt-2">
                <p className="text-xs text-muted-foreground">Friendly reminder: If your itinerary changes and you need to apply for partial cancellation, please consult our customer service team by <button className="text-primary underline" onClick={() => { setTicketBooking(selectedBooking); setTicketOpen(true); setSelectedBooking(null); }}>submitting a ticket</button>.</p>
                <div className="flex gap-2 shrink-0 ml-4">
                  {selectedBooking.bookingStatus !== "Cancelled" && (
                    <Button variant="outline" size="sm" className="border-red-300 text-red-500 hover:bg-red-50" onClick={() => {
                      if (new Date(selectedBooking.cancelDeadline) > new Date()) setCancelOpen(true);
                      else toast.error("Cancellation deadline has passed.", { description: "Full charge will be applied." });
                    }}>Cancel</Button>
                  )}
                  <Button size="sm" style={{ background: "#FF6000" }} onClick={() => { setTicketBooking(selectedBooking); setTicketOpen(true); setSelectedBooking(null); }}>Submit Ticket</Button>
                </div>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* ── Export History Dialog ── */}
      <Dialog open={exportHistoryOpen} onOpenChange={setExportHistoryOpen}>
        <DialogContent className="max-w-2xl">
          <DialogHeader><DialogTitle>Export History</DialogTitle></DialogHeader>
          {exportHistoryList.length === 0 ? (
            <div className="py-8 text-center text-sm text-muted-foreground">
              <FileText className="h-10 w-10 mx-auto mb-2 opacity-30" />
              <p>No export history yet.</p>
              <p className="text-xs mt-1">Exported files will appear here (last 20 exports).</p>
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>File Name</TableHead>
                  <TableHead>Date</TableHead>
                  <TableHead>Records</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead></TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {exportHistoryList.map(e => (
                  <TableRow key={e.id}>
                    <TableCell className="text-xs font-mono truncate max-w-[240px]" title={e.fileName}>{e.fileName}</TableCell>
                    <TableCell className="text-xs">{e.date}</TableCell>
                    <TableCell className="text-xs">{e.records}</TableCell>
                    <TableCell><Badge variant={e.status === "Completed" ? "default" : "secondary"} className="text-[10px]">{e.status}</Badge></TableCell>
                    <TableCell>
                      {e.status === "Completed" ? (
                        <Button size="sm" variant="ghost" className="h-6 text-xs" onClick={() => { if (redownloadExport(e.id)) toast.success("Re-downloading..."); else toast.error("File no longer available"); }}>
                          <Download className="h-3 w-3 mr-1" />Download
                        </Button>
                      ) : (
                        <span className="text-xs text-muted-foreground italic">Expired</span>
                      )}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </DialogContent>
      </Dialog>

      {/* ── Cancel Dialog ──
       * 취소 사유 입력 필드는 의도적으로 제거. OP들이 귀찮아서 "Other"만
       * 선택하면 수집된 데이터 무의미. 취소 자체의 확인에만 집중. */}
      <AlertDialog open={cancelOpen} onOpenChange={setCancelOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Cancel Booking</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to cancel this booking? Cancellation fees may apply
              according to the hotel policy.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction className="bg-destructive text-destructive-foreground hover:bg-destructive/90" onClick={() => {
              if (selectedBooking) {
                const d = new Date();
                const pad = (n: number) => String(n).padStart(2, "0");
                const now = `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
                setLocalBookings(prev => prev.map(b => b.id === selectedBooking.id ? { ...b, bookingStatus: "Cancelled" as const, cancelDate: now, paymentStatus: b.paymentStatus === "Fully Paid" ? "Refunded" as const : b.paymentStatus } : b));
              }
              toast.success("Booking Cancelled", { description: "The booking has been cancelled and a notification has been created." });
              setSelectedBooking(null);
            }}>Confirm Cancellation</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* ── (Amend Booking removed — bookings cannot be modified) ── */}

      {/* ── Booking Voucher Dialog (A4) ── */}
      <Dialog open={voucherOpen} onOpenChange={setVoucherOpen}>
        <DialogContent className="max-h-[95vh] overflow-y-auto p-0" style={{ maxWidth: "900px", width: "90vw" }}>
          <DialogHeader className="px-6 pt-4 pb-2 border-b"><DialogTitle>Booking Voucher</DialogTitle></DialogHeader>
          {/* Voucher Options Bar (non-printable) */}
          <div className="px-6 py-3 border-b flex items-center gap-6 flex-wrap bg-muted/30 no-print">
            <label className="flex items-center gap-2 text-sm cursor-pointer">
              <Checkbox checked={voucherShowClientLogo} onCheckedChange={c => setVoucherShowClientLogo(!!c)} />
              Show your company info
            </label>
            <label className="flex items-center gap-2 text-sm cursor-pointer">
              <Checkbox checked={voucherShowLogo} onCheckedChange={c => setVoucherShowLogo(!!c)} />
              Show OhMyHotel info
            </label>
            <label className="flex items-center gap-2 text-sm cursor-pointer">
              <Checkbox checked={voucherShowQR} onCheckedChange={c => setVoucherShowQR(!!c)} />
              Show hotel QR code
            </label>
            <div className="flex items-center gap-2 text-sm">
              <span className="text-muted-foreground">Language:</span>
              {(["EN", "KO", "JA", "ZH", "VI"] as const).map(lang => (
                <label key={lang} className="flex items-center gap-1 cursor-pointer">
                  <input type="radio" name="voucherLang" checked={voucherLang === lang} onChange={() => setVoucherLang(lang)} className="accent-[#FF6000]" />
                  <span className={voucherLang === lang ? "text-[#FF6000] font-medium" : ""}>{lang}</span>
                </label>
              ))}
            </div>
          </div>
          {selectedBooking && (() => {
            const checkOutDate = (() => { const d = new Date(selectedBooking.checkIn); d.setDate(d.getDate() + selectedBooking.nights); return d.toISOString().split("T")[0]; })();
            const ciDay = new Date(selectedBooking.checkIn).toLocaleDateString("en-US", { weekday: "short" }).toUpperCase();
            const coDay = new Date(checkOutDate).toLocaleDateString("en-US", { weekday: "short" }).toUpperCase();
            /* Translations */
            const L: Record<string, Record<string, string>> = {
              title: { EN: "Voucher", KO: "바우처", JA: "バウチャー", ZH: "凭证", VI: "Phiếu xác nhận" },
              bookingInfo: { EN: "Booking Information", KO: "예약 정보", JA: "予約情報", ZH: "预订信息", VI: "Thông tin đặt phòng" },
              refNo: { EN: "Reference No.", KO: "예약 번호", JA: "参照番号", ZH: "参考编号", VI: "Số tham chiếu" },
              bookingCode: { EN: "Booking Code", KO: "예약 코드", JA: "予約コード", ZH: "预订码", VI: "Mã đặt phòng" },
              hotel: { EN: "Hotel", KO: "호텔", JA: "ホテル", ZH: "酒店", VI: "Khách sạn" },
              address: { EN: "Address", KO: "주소", JA: "住所", ZH: "地址", VI: "Địa chỉ" },
              tel: { EN: "Tel.", KO: "전화번호", JA: "電話番号", ZH: "电话", VI: "Điện thoại" },
              rooms: { EN: "Rooms", KO: "객실", JA: "部屋数", ZH: "房间数", VI: "Phòng" },
              checkIn: { EN: "Check In", KO: "체크인", JA: "チェックイン", ZH: "入住", VI: "Nhận phòng" },
              checkOut: { EN: "Check Out", KO: "체크아웃", JA: "チェックアウト", ZH: "退房", VI: "Trả phòng" },
              roomType: { EN: "Room Type", KO: "객실 유형", JA: "客室タイプ", ZH: "房型", VI: "Loại phòng" },
              mealType: { EN: "Meal & Breakfast Type", KO: "식사/조식", JA: "食事・朝食", ZH: "餐食/早餐", VI: "Bữa ăn/Ăn sáng" },
              guests: { EN: "Guests", KO: "투숙객", JA: "宿泊者", ZH: "客人", VI: "Khách" },
              guestReq: { EN: "Guest Requests", KO: "요청사항", JA: "リクエスト", ZH: "客户要求", VI: "Yêu cầu" },
              roomOnly: { EN: "Room Only", KO: "객실만", JA: "客室のみ", ZH: "仅客房", VI: "Chỉ phòng" },
              noRequests: { EN: "No additional requests", KO: "추가 요청사항 없음", JA: "追加リクエストなし", ZH: "无附加要求", VI: "Không có yêu cầu" },
              guidelines: { EN: "[Guidelines]", KO: "[안내사항]", JA: "[ご案内]", ZH: "[注意事项]", VI: "[Hướng dẫn]" },
            };
            const t = (k: string) => L[k]?.[voucherLang] || L[k]?.EN || k;
            return (
              <div id="printable-voucher" className="bg-white text-slate-900 p-10" style={{ fontFamily: "Arial, sans-serif" }}>
                {/* Client Company Header (toggleable, default ON) */}
                {voucherShowClientLogo && (
                  <div className="flex items-center gap-6 rounded p-4 mb-5" style={{ border: "2px solid #FF6000", background: "#fff7ed" }}>
                    <div className="flex items-center gap-3">
                      <div className="w-12 h-12 rounded shrink-0 flex items-center justify-center text-white text-lg font-bold" style={{ background: "#FF6000" }}>
                        {voucherSettings.companyName.charAt(0)}
                      </div>
                      <div>
                        <div className="text-lg font-bold text-slate-900">{voucherSettings.companyName}</div>
                        <div className="text-[11px] text-slate-600">{voucherSettings.address}</div>
                      </div>
                    </div>
                    <div className="text-xs text-slate-700 ml-auto">
                      {voucherSettings.phone && <p>Tel: {voucherSettings.phone}</p>}
                      {voucherSettings.email && <p>Email: <span className="text-blue-600">{voucherSettings.email}</span></p>}
                    </div>
                  </div>
                )}
                {/* OhMyHotel Header (toggleable, default OFF) */}
                {voucherShowLogo && (
                  <div className="flex items-center gap-6 border border-slate-300 rounded p-4 mb-5">
                    <div className="flex items-center gap-2">
                      <div className="relative w-10 h-10 shrink-0">
                        <div className="absolute inset-0 rounded-full" style={{ background: "conic-gradient(from 180deg, #FF6000, #FF8C00, #FFCF8F, #FF6000)" }} />
                        <div className="absolute inset-[2px] rounded-full bg-white flex items-center justify-center">
                          <svg viewBox="0 0 24 24" className="w-5 h-5" fill="none"><path d="M12 3C7.5 3 4 6.5 4 11c0 3 1.5 5.5 4 7l1-2c-2-1-3-3-3-5 0-3.3 2.7-6 6-6s6 2.7 6 6c0 2-1 3.8-2.5 5l1 2c2.3-1.5 3.5-4 3.5-7 0-4.5-3.5-8-8-8z" fill="#FF6000" /><circle cx="12" cy="4" r="2.5" fill="#009505" /></svg>
                        </div>
                      </div>
                      <span className="text-xl font-bold" style={{ color: "#FF6000" }}>OhMyHotel</span>
                    </div>
                    <div className="text-xs text-slate-700">
                      <p>Tel: +82-2-762-0552</p>
                      <p>Email: <span className="text-blue-600">support@ohmyhotel.com</span></p>
                    </div>
                  </div>
                )}
                {/* Title */}
                <div className="mb-6 flex items-center justify-between">
                  <h1 className="text-3xl font-bold" style={{ color: "#FF6000" }}>{t("title")}</h1>
                  {voucherShowQR && (
                    <div className="text-center">
                      <div className="w-20 h-20 bg-white border-2 border-slate-900 p-1.5">
                        <div className="w-full h-full grid grid-cols-8 gap-[1px]">
                          {Array.from({ length: 64 }).map((_, i) => (<div key={i} className={Math.random() > 0.5 ? "bg-slate-900" : "bg-white"} />))}
                        </div>
                      </div>
                      <p className="text-[9px] text-slate-600 mt-1">Scan for more</p>
                    </div>
                  )}
                </div>

                {/* Booking Information */}
                <h2 className="text-xl font-bold border-b-2 pb-2 mb-4" style={{ borderColor: "#FF6000" }}>{t("bookingInfo")}</h2>
                <table className="w-full mb-8 text-sm">
                  <tbody>
                    <tr className="border-b"><td className="py-2.5 font-medium text-slate-600 w-48">{t("refNo")}</td><td className="py-2.5 text-slate-900 font-medium">{selectedBooking.ellisCode} / {selectedBooking.hotelConfirmCode || "—"}</td></tr>
                    <tr className="border-b"><td className="py-2.5 font-medium text-slate-600">{t("bookingCode")}</td><td className="py-2.5 font-mono">{selectedBooking.ellisCode}</td></tr>
                    <tr className="border-b"><td className="py-2.5 font-medium text-slate-600">{t("hotel")}</td><td className="py-2.5 font-medium">{selectedBooking.hotelName}</td></tr>
                    <tr className="border-b"><td className="py-2.5 font-medium text-slate-600">{t("address")}</td><td className="py-2.5">{selectedBooking.hotelAddress}</td></tr>
                    <tr className="border-b"><td className="py-2.5 font-medium text-slate-600">{t("tel")}</td><td className="py-2.5">{selectedBooking.hotelContact}</td></tr>
                    <tr className="border-b"><td className="py-2.5 font-medium text-slate-600">{t("rooms")}</td><td className="py-2.5">{selectedBooking.roomCount}</td></tr>
                    <tr className="border-b"><td className="py-2.5 font-medium text-slate-600">{t("checkIn")}</td><td className="py-2.5 text-green-700 font-medium">{selectedBooking.checkIn}({ciDay})</td></tr>
                    <tr className="border-b"><td className="py-2.5 font-medium text-slate-600">{t("checkOut")}</td><td className="py-2.5 text-green-700 font-medium">{checkOutDate}({coDay})</td></tr>
                    <tr className="border-b"><td className="py-2.5 font-medium text-slate-600">{t("roomType")}</td><td className="py-2.5">{selectedBooking.roomType}</td></tr>
                    <tr className="border-b"><td className="py-2.5 font-medium text-slate-600">{t("mealType")}</td><td className="py-2.5">{t("roomOnly")}</td></tr>
                    <tr className="border-b"><td className="py-2.5 font-medium text-slate-600">{t("guests")}</td><td className="py-2.5"><div className="font-medium">Room 1</div><div className="text-slate-700">{selectedBooking.traveler.split(" ").join("/")}, TBAAB/TBAAB</div></td></tr>
                    <tr className="border-b"><td className="py-2.5 font-medium text-slate-600">{t("guestReq")}</td><td className="py-2.5">{selectedBooking.specialRequests || t("noRequests")}</td></tr>
                  </tbody>
                </table>

                {/* Guidelines */}
                <div className="bg-orange-50 border border-orange-200 rounded p-4 mb-6">
                  <h3 className="text-sm font-bold text-red-600 mb-2">{t("guidelines")}</h3>
                  <ul className="space-y-1.5 text-xs text-slate-700">
                    <li className="flex gap-2"><span className="text-orange-600 shrink-0">\u2611</span>Please present the Voucher to the Front desk along with your passport when checking in at the accommodation.</li>
                    <li className="flex gap-2"><span className="text-orange-600 shrink-0">\u2611</span>Please check your Reservation details before cancelling as Cancellation charge can be applied. In case you do not check in on the check-in date, we will treat this as No-show and your payment will not be refunded. For smooth check-in, please contact the hotel in advance for late check-in after 9pm hotel local time.</li>
                    <li className="flex gap-2"><span className="text-orange-600 shrink-0">\u2611</span>A room type set for 3 people allows up to 3 people to stay in 1 room, and does not necessarily mean that 3 beds are provided. In some cases, only one double bed or two single beds are provided without an extra bed/mattress, and breakfast can only be provided for two people.</li>
                    <li className="flex gap-2"><span className="text-orange-600 shrink-0">\u2611</span>Based on the Policies of each hotel, a deposit amount might be required in cash or card. If there is no usage history for the in-room billing service and facilities, the hotel will check and process a refund upon departure.</li>
                    <li className="flex gap-2"><span className="text-orange-600 shrink-0">\u2611</span>According to local tax regulation in some cities, accommodation tax/city tax/bathing tax, etc. surcharge might be required upon check-in. In addition, additional charges may be incurred due to write-offs/compulsory gala dinners for specific dates. Hotels reserve the right to deny access or apply additional surcharge for unresevred personnel(including infants).</li>
                    <li className="flex gap-2"><span className="text-orange-600 shrink-0">\u2611</span>Membership point/mileage benefits and accumulation operated by the hotel itself are invalid.</li>
                  </ul>
                </div>

                {/* Footer */}
                <div className="border-t pt-4 text-xs text-slate-700 space-y-3">
                  <div>
                    <p className="font-bold text-slate-900 mb-1">Site Operator</p>
                    <p>OHMYHOTEL GLOBAL PTE. LTD. (Business Registration No. 202543984E, CEO: LEE MISOON)</p>
                    <p>111 SOMERSET ROAD, #06-01H, 111 SOMERSET, SINGAPORE 238164</p>
                  </div>
                  <div>
                    <p className="font-bold text-slate-900 mb-1">Customer Service Center</p>
                    <p>OHMYHOTEL &amp; CO., Ltd. (Business Registration No. 105-87-71311, CEO: Lee Misoon)</p>
                    <p>GT Dongdaemun Building 6F, 328 Jongno, Jongno-gu, Seoul, Republic of Korea (Changsin-dong 330-1)</p>
                    <p>Tel: +82-2-762-0552 (Korea Weekdays 09:00 ~ 18:00, Closed on Weekends &amp; Public Holidays)</p>
                    <p>E-Commerce Registration No.: 2020-Seoul Jongno-0399 | Privacy Officer: Lee Misoon</p>
                  </div>
                  <p className="text-slate-500 pt-2 border-t">© 2026 OHMYHOTEL GLOBAL PTE. LTD. All rights reserved.</p>
                </div>
              </div>
            );
          })()}
          <div className="flex justify-end gap-2 px-6 py-3 border-t bg-muted/30 sticky bottom-0">
            <Button variant="outline" onClick={() => setVoucherOpen(false)}>Close</Button>
            <Button style={{ background: "#FF6000" }} onClick={() => window.print()}><Printer className="h-4 w-4 mr-1" />Print / Save PDF</Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* ── Group Booking Dialog ── */}
      {/* GroupBookingDialog removed */}

      {/* Create Ticket Dialog */}
      <CreateTicketDialog open={ticketOpen} onOpenChange={setTicketOpen} bookingCode={ticketBooking?.ellisCode} hotelName={ticketBooking?.hotelName} />

      <StateToolbar state={state} setState={setState} />
    </div>
  );
}
