/* Alert system mock.
 *
 * Alerts are derived events surfaced to customers (and potentially admin).
 * In production these would be:
 *   - Generated by ELLIS background workers (cron + event-driven)
 *   - Persisted in alerts table
 *   - Pushed via channels (in-app/email/SMS/Slack)
 *
 * For DOTBIZ prototype, we seed realistic alerts that the customer can
 * see in the Bell icon dropdown / Notifications page.
 *
 * Spec: docs/specs/dotbiz/AlertSystem.md
 */

export type AlertCategory = "Settlement" | "Booking" | "Dispute" | "Account" | "System";

export type AlertPriority = "P0" | "P1" | "P2" | "P3";

export type AlertChannel = "In-app" | "Email" | "SMS" | "Slack";

/* All alert types DOTBIZ supports */
export type AlertType =
  /* P0 — Critical (settlement) */
  | "credit_low"            /* Credit available ≤ Low threshold */
  | "credit_critical"       /* Credit ≤ Critical threshold */
  | "invoice_overdue"       /* POSTPAY invoice past due date */
  | "topup_confirmed"       /* Wire received & matched */
  | "topup_expired"         /* No wire within 7 days */
  /* P0 — Critical (booking) */
  | "prepay_deadline_d7" | "prepay_deadline_d3" | "prepay_deadline_d1" | "prepay_deadline_dday"
  | "booking_auto_cancelled"  /* PREPAY payment deadline missed — auto-cancel executed */
  | "booking_cancelled_by_hotel"
  | "partial_payment_detected"
  /* P1 — Important */
  | "invoice_due_soon"       /* D-2 soft reminder before POSTPAY invoice dueDate */
  | "topup_pending_reminder" /* D+5 — top-up requested but no wire yet */
  | "invoice_issued"
  | "payment_received"
  | "dispute_opened"
  | "dispute_resolved"
  | "ticket_reply"
  | "checkin_tomorrow"
  | "credit_note_issued"
  /* P2 — Useful */
  | "subaccount_added"
  | "role_changed"
  | "contract_amendment"
  /* P2 — Rewards Mall (OP-personal) */
  | "points_earned"          /* Booking confirmed → +N points credited to OP */
  | "points_milestone"       /* Cumulative-booking milestone reached */
  | "points_expiring"        /* D-30 / D-7 before voucher or points expire */
  | "reward_redeemed"        /* Voucher code issued */
  /* P1 — Booking volume anomalies (applies to UI + API partners) */
  | "booking_volume_spike"   /* Usual baseline 10/day but today 20+ — check for abuse or miscount */
  | "booking_volume_drop";   /* Usual baseline 10/day but today 0 — check integration or partner health */

export interface Alert {
  id: string;
  type: AlertType;
  category: AlertCategory;
  priority: AlertPriority;
  customerCompanyId: string;
  contractId?: string;     /* Some alerts are contract-scoped */
  title: string;
  body: string;
  /* Action link (deep link inside DOTBIZ) */
  actionLabel?: string;
  actionPath?: string;     /* e.g. /app/settlement/invoice/INV-2026-0089 */
  /* Channels that were sent */
  sentVia: AlertChannel[];
  createdAt: string;
  readAt?: string;
  dismissed?: boolean;
  /* Reference data for the source (so UI can deep-link or rerender) */
  refType?: "invoice" | "booking" | "ticket" | "contract" | "topup";
  refId?: string;
}

/* Seed alerts — covers all P0/P1 types for demo */
export const alerts: Alert[] = [
  /* ── TravelCo (comp-001) — POSTPAY single-contract ── */
  {
    id: "alt-001",
    type: "invoice_overdue",
    category: "Settlement", priority: "P0",
    customerCompanyId: "comp-001", contractId: "ctr-001-sg",
    title: "Invoice INV-2025-0076 is 60+ days overdue",
    body: "USD 29,400 from October 2025 remains unpaid. Please remit immediately to avoid collections team escalation.",
    actionLabel: "View invoice", actionPath: "/app/settlement/invoice/INV-2025-0076",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-19 09:00:00",
    refType: "invoice", refId: "INV-2025-0076",
  },
  {
    id: "alt-002",
    type: "partial_payment_detected",
    category: "Settlement", priority: "P0",
    customerCompanyId: "comp-001", contractId: "ctr-001-sg",
    title: "Partial payment detected on INV-2026-0089",
    body: "Received USD 2,820 against USD 4,180. 2 bookings appear to have been excluded — please confirm via support if any of them are disputed.",
    actionLabel: "View invoice", actionPath: "/app/settlement/invoice/INV-2026-0089",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-15 14:25:00",
    refType: "invoice", refId: "INV-2026-0089",
  },
  {
    id: "alt-003",
    type: "invoice_issued",
    category: "Settlement", priority: "P1",
    customerCompanyId: "comp-001", contractId: "ctr-001-sg",
    title: "New invoice issued: INV-2026-0130 — USD 10,630",
    body: "Your bi-weekly settlement invoice for April 2026 is ready. Due 2026-05-31.",
    actionLabel: "Open invoice", actionPath: "/app/settlement/invoice/INV-2026-0130",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-05-01 01:05:00",
    readAt: "2026-05-01 09:32:11",
    refType: "invoice", refId: "INV-2026-0130",
  },

  /* ── Asia Tours (comp-002) — PREPAY ── */
  {
    id: "alt-010",
    type: "prepay_deadline_dday",
    category: "Booking", priority: "P0",
    customerCompanyId: "comp-002", contractId: "ctr-002-sg",
    title: "Payment due TODAY — Park Hyatt Saigon",
    body: "Booking K26040109301H01 (USD 920) requires payment by 17:00 KST. After deadline, the booking is auto-cancelled.",
    actionLabel: "Pay now", actionPath: "/app/settlement",
    sentVia: ["In-app", "Email", "SMS"],
    createdAt: "2026-04-20 08:00:00",
    refType: "booking", refId: "K26040109301H01",
  },
  {
    id: "alt-011",
    type: "prepay_deadline_d3",
    category: "Booking", priority: "P0",
    customerCompanyId: "comp-002", contractId: "ctr-002-sg",
    title: "Payment due in 3 days — Raffles Singapore",
    body: "Booking K26040816352H01 (USD 1,650) is unpaid. Settle the full amount by 2026-04-25 or the booking will be auto-cancelled.",
    actionLabel: "Pay now", actionPath: "/app/settlement",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-22 09:00:00",
    refType: "booking", refId: "K26040816352H01",
  },

  /* Historical: auto-cancelled booking (PREPAY deadline missed) */
  {
    id: "alt-012",
    type: "booking_auto_cancelled",
    category: "Booking", priority: "P0",
    customerCompanyId: "comp-002", contractId: "ctr-002-sg",
    title: "Booking auto-cancelled: Hotel Nikko Bangkok — deadline missed",
    body: "K26031511457H01 (check-in 2026-03-18, Tanaka Yuki) was auto-cancelled on 2026-03-17 17:00 KST after the payment deadline was missed. USD 780 forfeited per non-refundable terms. Please contact the guest with alternate arrangements.",
    actionLabel: "View booking", actionPath: "/app/bookings/bk-003",
    sentVia: ["In-app", "Email", "SMS"],
    createdAt: "2026-03-17 17:00:30",
    readAt: "2026-03-17 17:14:22",
    refType: "booking", refId: "K26031511457H01",
  },

  /* ── GOTADI (comp-010) — multi-entity, leverage credit (Bank Guarantee) — but Floating, low alert ── */
  {
    id: "alt-020",
    type: "topup_confirmed",
    category: "Settlement", priority: "P1",
    customerCompanyId: "comp-001", contractId: "ctr-001-sg",
    title: "Top-up confirmed: USD +20,000",
    body: "TUP-20260418-A4F7 reconciled. Available credit increased to USD 35,400.",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-19 14:22:08",
    readAt: "2026-04-19 16:00:00",
    refType: "topup", refId: "TUP-20260418-A4F7",
  },
  {
    id: "alt-021",
    type: "credit_low",
    category: "Settlement", priority: "P0",
    customerCompanyId: "comp-010", contractId: "ctr-010-sg",
    title: "Credit running low — only USD 7,200 available",
    body: "Your USD contract with OhMyHotel SG is at 82% utilization. Consider topping up your Floating Deposit before reaching the limit.",
    actionLabel: "Top up", actionPath: "/app/settlement",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-20 06:00:00",
    refType: "contract", refId: "ctr-010-sg",
  },

  /* ── Booking events ── */
  {
    id: "alt-030",
    type: "booking_cancelled_by_hotel",
    category: "Booking", priority: "P0",
    customerCompanyId: "comp-001",
    title: "Hotel cancelled: K26040514508H01 InterContinental Da Nang",
    body: "The hotel reported overbooking and cancelled this booking (check-in 2026-04-08, Tom Wilson). A support ticket has been opened on your behalf — our team will coordinate any refund or compensation per our SLA. Please reply to the ticket with any constraints on alternate dates or hotels.",
    actionLabel: "View booking", actionPath: "/app/bookings/K26040514508H01",
    sentVia: ["In-app", "Email", "SMS"],
    createdAt: "2026-04-09 11:30:00",
    refType: "booking", refId: "K26040514508H01",
  },
  {
    id: "alt-031",
    type: "checkin_tomorrow",
    category: "Booking", priority: "P1",
    customerCompanyId: "comp-001",
    title: "Check-in tomorrow: 2 guests at Grand Hyatt Seoul",
    body: "John Smith and Sarah Kim arrive 2026-04-21. Hotel confirmation HC-GHS-9821.",
    actionLabel: "View bookings", actionPath: "/app/bookings",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-20 07:00:00",
    readAt: "2026-04-20 08:15:00",
  },
  /* ── Dispute & ticket ── */
  {
    id: "alt-040",
    type: "dispute_opened",
    category: "Dispute", priority: "P1",
    customerCompanyId: "comp-001",
    title: "Dispute flagged on K26032209155H01 (Shilla Stay Mapo)",
    body: "Reason: Room type mismatch. Linked ticket: TK-2026-007. Our team is investigating.",
    actionLabel: "View ticket", actionPath: "/app/tickets?highlight=TK-2026-007",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-05 11:48:22",
    refType: "ticket", refId: "TK-2026-007",
  },
  {
    id: "alt-041",
    type: "ticket_reply",
    category: "Dispute", priority: "P1",
    customerCompanyId: "comp-001",
    title: "Reply on TK-2026-007",
    body: "Sarah Kim (OP) responded — please review and confirm.",
    actionLabel: "Open ticket", actionPath: "/app/tickets?highlight=TK-2026-007",
    sentVia: ["In-app"],
    createdAt: "2026-04-18 14:30:00",
    refType: "ticket", refId: "TK-2026-007",
  },
  {
    id: "alt-042",
    type: "credit_note_issued",
    category: "Settlement", priority: "P1",
    customerCompanyId: "comp-001",
    title: "Credit note issued: CN-2026-0001 USD -780",
    body: "Issued against INV-2026-0089 for Nikko Bangkok no-show waiver. Will be applied to next bi-weekly invoice.",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-17 15:22:00",
    refType: "invoice", refId: "INV-2026-0089",
  },

  /* ── Account ── */
  {
    id: "alt-050",
    type: "subaccount_added",
    category: "Account", priority: "P2",
    customerCompanyId: "comp-001",
    title: "Sub-account added: emily@travelco.com",
    body: "Role: OP. Added by Master James Park.",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-12 10:15:00",
    readAt: "2026-04-12 10:30:00",
  },
  {
    id: "alt-051",
    type: "contract_amendment",
    category: "Account", priority: "P2",
    customerCompanyId: "comp-001", contractId: "ctr-001-sg",
    title: "Settlement cycle changed: Monthly → Bi-weekly",
    body: "Effective from 2026-04-01, payment due days shortened from Net-14 to Net-5 (issued Bi-weekly). Contact your account manager with questions.",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-03-25 09:00:00",
    readAt: "2026-03-25 11:00:00",
  },

  /* ════════════════════════════════════════════════════════════════
   * ADDITIONAL SEEDS — broader coverage across customers + alert types
   * Demo today = 2026-04-22
   * ════════════════════════════════════════════════════════════════ */

  /* ─── TravelCo (comp-001) — more Settlement variety ─── */
  {
    id: "alt-060",
    type: "invoice_due_soon",
    category: "Settlement", priority: "P1",
    customerCompanyId: "comp-001", contractId: "ctr-001-sg",
    title: "Invoice due in 2 days — INV-2026-0142",
    body: "USD 5,350 is due 2026-04-25. Please prepare your wire transfer.",
    actionLabel: "View invoice", actionPath: "/app/settlement/invoice/INV-2026-0142",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-23 08:00:00",
    refType: "invoice", refId: "INV-2026-0142",
  },
  {
    id: "alt-061",
    type: "invoice_overdue",
    category: "Settlement", priority: "P0",
    customerCompanyId: "comp-001", contractId: "ctr-001-sg",
    title: "Invoice INV-2026-0118 overdue — 12 days",
    body: "USD 4,180 was due 2026-04-10. New bookings will be paused if unpaid by D+10 (2026-04-20). Please remit immediately.",
    actionLabel: "View invoice", actionPath: "/app/settlement/invoice/INV-2026-0118",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-22 09:00:00",
    refType: "invoice", refId: "INV-2026-0118",
  },
  {
    id: "alt-062",
    type: "payment_received",
    category: "Settlement", priority: "P1",
    customerCompanyId: "comp-001", contractId: "ctr-001-sg",
    title: "Payment received: USD 2,970 — INV-2026-0156",
    body: "Wire transfer received and reconciled. Invoice marked as Fully Paid.",
    sentVia: ["In-app"],
    createdAt: "2026-04-21 16:44:02",
    readAt: "2026-04-21 17:22:10",
    refType: "invoice", refId: "INV-2026-0156",
  },
  {
    id: "alt-063",
    type: "topup_pending_reminder",
    category: "Settlement", priority: "P1",
    customerCompanyId: "comp-001",
    title: "Top-up wire still pending — TUP-SG-20260416-B2C1",
    body: "5 days since request. No matching wire received yet. This reference code expires in 2 days if no wire arrives.",
    actionLabel: "View top-ups", actionPath: "/app/settlement",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-21 09:00:00",
    refType: "topup", refId: "TUP-SG-20260416-B2C1",
  },
  {
    id: "alt-064",
    type: "invoice_issued",
    category: "Settlement", priority: "P1",
    customerCompanyId: "comp-001", contractId: "ctr-001-sg",
    title: "New invoice issued: INV-2026-0142 — USD 5,350",
    body: "Your bi-weekly settlement for Apr 2026 H1 is ready. Due 2026-04-25.",
    actionLabel: "Open invoice", actionPath: "/app/settlement/invoice/INV-2026-0142",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-20 01:00:44",
    readAt: "2026-04-20 08:12:30",
    refType: "invoice", refId: "INV-2026-0142",
  },
  {
    id: "alt-065",
    type: "dispute_resolved",
    category: "Dispute", priority: "P1",
    customerCompanyId: "comp-001",
    title: "Dispute resolved (Approved): K26040514508H01 — USD 130",
    body: "Your no-show ticket TK-2026-003 was approved. A credit note has been issued for the excluded cancellation fee.",
    actionLabel: "View ticket", actionPath: "/app/tickets?highlight=TK-2026-003",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-19 14:20:00",
    refType: "ticket", refId: "TK-2026-003",
  },
  {
    id: "alt-066",
    type: "role_changed",
    category: "Account", priority: "P2",
    customerCompanyId: "comp-001",
    title: "Your role changed: OP → Accounting",
    body: "James Park updated your role on 2026-04-18. You now have access to Settlement pages. Refresh to pick up new permissions.",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-18 11:20:00",
    readAt: "2026-04-18 11:45:12",
  },

  /* ─── Asia Tours (comp-002) — PREPAY scenarios ─── */
  {
    id: "alt-110",
    type: "prepay_deadline_d7",
    category: "Booking", priority: "P0",
    customerCompanyId: "comp-002", contractId: "ctr-002-sg",
    title: "Payment due in 7 days — Ritz-Carlton Tokyo",
    body: "Booking K26041617051H01 (USD 3,800) payment deadline 2026-05-10. Pay early to avoid last-minute card decline.",
    actionLabel: "Pay now", actionPath: "/app/settlement",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-20 08:00:00",
    refType: "booking", refId: "K26041617051H01",
  },
  {
    id: "alt-111",
    type: "prepay_deadline_d1",
    category: "Booking", priority: "P0",
    customerCompanyId: "comp-002", contractId: "ctr-002-sg",
    title: "🚨 Final reminder — Payment due TOMORROW",
    body: "Booking K26032510083H01 Mandarin Oriental Tokyo (USD 2,400) requires payment by 2026-04-23 17:00 KST. Free cancellation has passed — non-refundable now. USD 2,400 will be FORFEITED if unpaid.",
    actionLabel: "Pay now", actionPath: "/app/settlement",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-22 09:00:00",
    refType: "booking", refId: "K26032510083H01",
  },
  {
    id: "alt-113",
    type: "ticket_reply",
    category: "Dispute", priority: "P1",
    customerCompanyId: "comp-002",
    title: "3 new replies on TK-2026-012",
    body: "Kevin Lee (OP) and Jennifer Wu responded. Please review the updated recommendation.",
    actionLabel: "Open ticket", actionPath: "/app/tickets?highlight=TK-2026-012",
    sentVia: ["In-app"],
    createdAt: "2026-04-22 11:30:00",
    refType: "ticket", refId: "TK-2026-012",
  },
  {
    id: "alt-114",
    type: "subaccount_added",
    category: "Account", priority: "P2",
    customerCompanyId: "comp-002",
    title: "Sub-account added: alex@asiatours.com",
    body: "Role: OP. Added by Jennifer Wu (Master).",
    sentVia: ["In-app"],
    createdAt: "2025-03-30 14:22:00",
    readAt: "2025-03-30 15:00:00",
  },

  /* ─── GOTADI (comp-010) — multi-entity variety (both SG and VN) ─── */
  {
    id: "alt-210",
    type: "credit_critical",
    category: "Settlement", priority: "P0",
    customerCompanyId: "comp-010", contractId: "ctr-010-sg",
    title: "🔴 Critical credit — only USD 2,800 available",
    body: "Your SG contract credit is below critical threshold (USD 5,000). New bookings exceeding USD 2,800 will be hard-blocked. Top up immediately or settle outstanding invoices.",
    actionLabel: "Top up now", actionPath: "/app/settlement",
    sentVia: ["In-app", "Email", "SMS"],
    createdAt: "2026-04-22 07:00:00",
    refType: "contract", refId: "ctr-010-sg",
  },
  {
    id: "alt-211",
    type: "invoice_issued",
    category: "Settlement", priority: "P1",
    customerCompanyId: "comp-010", contractId: "ctr-010-vn",
    title: "New invoice issued: INV-VN-2026-0455 — VND 280,000,000",
    body: "Vietnam hotels · VAT 10% included · issued by OhMyHotel VN. Due 2026-04-25 (Net-5). Wire to Vietcombank HCMC.",
    actionLabel: "Open invoice", actionPath: "/app/settlement/invoice/INV-VN-2026-0455",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-20 01:00:40",
    readAt: "2026-04-20 09:15:22",
    refType: "invoice", refId: "INV-VN-2026-0455",
  },
  {
    id: "alt-212",
    type: "partial_payment_detected",
    category: "Settlement", priority: "P0",
    customerCompanyId: "comp-010", contractId: "ctr-010-vn",
    title: "Partial payment detected — INV-VN-2026-0445",
    body: "Received VND 85,000,000 against VND 190,000,000. VND 105,000,000 outstanding. Please confirm via support if any bookings are under dispute.",
    actionLabel: "View invoice", actionPath: "/app/settlement/invoice/INV-VN-2026-0445",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-12 14:30:00",
    readAt: "2026-04-12 15:00:00",
    refType: "invoice", refId: "INV-VN-2026-0445",
  },
  {
    id: "alt-213",
    type: "topup_confirmed",
    category: "Settlement", priority: "P1",
    customerCompanyId: "comp-010", contractId: "ctr-010-vn",
    title: "Top-up confirmed: VND +500,000,000",
    body: "TUP-VN-20260410-D8E2 reconciled via Vietcombank. VN contract credit restored. Available now VND 280,000,000.",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-10 11:22:00",
    readAt: "2026-04-10 11:45:00",
    refType: "topup", refId: "TUP-VN-20260410-D8E2",
  },
  {
    id: "alt-214",
    type: "topup_expired",
    category: "Settlement", priority: "P0",
    customerCompanyId: "comp-010", contractId: "ctr-010-sg",
    title: "Top-up expired — TUP-SG-20260408-F3A9",
    body: "USD 30,000 top-up request expired. No bank wire received within 7 days. This reference code is no longer valid. Please create a new top-up request.",
    actionLabel: "New top-up", actionPath: "/app/settlement",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-15 09:00:00",
    readAt: "2026-04-15 10:30:00",
    refType: "topup", refId: "TUP-SG-20260408-F3A9",
  },
  {
    id: "alt-215",
    type: "dispute_opened",
    category: "Dispute", priority: "P1",
    customerCompanyId: "comp-010",
    title: "Dispute flagged on K26040509155H01 (Sofitel Saigon Plaza)",
    body: "Reason: Room not available on arrival. Linked ticket TK-2026-018. Our team is coordinating with the hotel.",
    actionLabel: "Open ticket", actionPath: "/app/tickets?highlight=TK-2026-018",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-20 16:40:00",
    refType: "ticket", refId: "TK-2026-018",
  },
  {
    id: "alt-216",
    type: "checkin_tomorrow",
    category: "Booking", priority: "P1",
    customerCompanyId: "comp-010",
    title: "Check-in tomorrow — 3 guests across 2 hotels",
    body: "Tomorrow (2026-04-23): 2 at Grand Hyatt Seoul, 1 at Lotte Hotel Hanoi. Click to view all.",
    actionLabel: "View bookings", actionPath: "/app/bookings",
    sentVia: ["In-app"],
    createdAt: "2026-04-22 08:00:00",
    refType: "booking",
  },

  /* ─── VVC (comp-011) — Pending + critical scenarios ─── */
  {
    id: "alt-310",
    type: "prepay_deadline_d3",
    category: "Booking", priority: "P0",
    customerCompanyId: "comp-011", contractId: "ctr-011-sg",
    title: "⚠️ Payment due in 3 days — Mandarin Oriental HK",
    body: "Booking K26041408382H01 (USD 2,100) — pay by 2026-04-28 or cancel by 2026-05-01 for full refund. After that, USD 2,100 is forfeited.",
    actionLabel: "Pay now", actionPath: "/app/settlement",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-22 09:00:00",
    refType: "booking", refId: "K26041408382H01",
  },
  {
    id: "alt-311",
    type: "invoice_issued",
    category: "Settlement", priority: "P1",
    customerCompanyId: "comp-011", contractId: "ctr-011-vn",
    title: "New invoice issued: INV-VN-PRE-2026-0521 — VND 165,000,000",
    body: "PREPAY · Metropole Hanoi · VAT 10% · OhMyHotel VN. Deadline 2026-05-05. Card or wire accepted.",
    actionLabel: "Open invoice", actionPath: "/app/settlement/invoice/INV-VN-PRE-2026-0521",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-20 16:22:41",
    refType: "invoice", refId: "INV-VN-PRE-2026-0521",
  },
  {
    id: "alt-312",
    type: "credit_low",
    category: "Settlement", priority: "P0",
    customerCompanyId: "comp-011",
    title: "Credit running low — VND 40M available",
    body: "Your VN contract credit is below the low threshold (VND 50M). Consider topping up before your next booking.",
    actionLabel: "Top up", actionPath: "/app/settlement",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-21 11:00:00",
    refType: "contract", refId: "ctr-011-vn",
  },

  /* ── Rewards (per-OP) — seed a few examples ── */
  {
    id: "alt-500",
    type: "points_earned",
    category: "Account", priority: "P2",
    customerCompanyId: "comp-001",
    title: "🔥 +2 P earned — Fairmont Singapore booking",
    body: "Your booking K26041511201H01 was confirmed. 2 points credited (Silver tier 1.1× applied). Balance: 185 P.",
    actionLabel: "View Rewards", actionPath: "/app/rewards",
    sentVia: ["In-app"],
    createdAt: "2026-04-20 11:22:18",
    readAt: "2026-04-20 11:25:00",
    refType: "booking", refId: "bk-016",
  },
  {
    id: "alt-501",
    type: "points_milestone",
    category: "Account", priority: "P1",
    customerCompanyId: "comp-010",
    title: "⭐ 50 Bookings milestone reached — Silver tier unlocked",
    body: "Congratulations on 50 bookings! +5 bonus points and you've advanced to Silver tier (1.1× earn multiplier from now on).",
    actionLabel: "View Rewards", actionPath: "/app/rewards",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-05 08:00:00",
    refType: undefined,
  },
  {
    id: "alt-502",
    type: "reward_redeemed",
    category: "Account", priority: "P2",
    customerCompanyId: "comp-001",
    title: "Redeemed: CGV 영화 관람권",
    body: "Voucher code CGV-9K4T-2XQB-7M3V issued — valid until 2026-07-15. Redeemed for 14 P.",
    actionLabel: "Open My Coupons", actionPath: "/app/rewards?tab=vault",
    sentVia: ["In-app"],
    createdAt: "2026-04-15 14:10:00",
    readAt: "2026-04-15 14:30:00",
  },
  {
    id: "alt-503",
    type: "points_expiring",
    category: "Account", priority: "P1",
    customerCompanyId: "comp-010",
    title: "Voucher expiring soon — GrabFood 100k VND",
    body: "Your GrabFood voucher GRAB-VN-FD-2K9M expires in 7 days (2026-06-15). Use it before it expires.",
    actionLabel: "Open My Coupons", actionPath: "/app/rewards?tab=vault",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-06-08 09:00:00",
  },

  /* ══ Booking Volume Anomaly — UI partner (TravelCo) ══
   * Spike: TravelCo normally runs ~8 bookings/day, but today hit 24 (3× baseline).
   * Anomaly detector flags it so Master can verify it's not duplicate/abuse. */
  {
    id: "alt-600",
    type: "booking_volume_spike",
    category: "Booking", priority: "P1",
    customerCompanyId: "comp-001",
    title: "Unusual booking volume — 24 bookings today (3× normal)",
    body: "TravelCo usually generates 8 bookings/day. Today saw 24 confirmed bookings — a 3.0× spike. Please verify this is expected (group/event booking, seasonal push) rather than duplicate entries.",
    actionLabel: "Review today's bookings", actionPath: "/app/bookings?filter=today",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-22 18:30:00",
    refType: "booking",
  },

  /* ══ Booking Volume Anomaly — API partner (GOTADI) ══
   * Drop: GOTADI connects via API and usually sends ~12 bookings/day, but 0 came
   * through in the last 24h — likely an integration outage or token expiry. */
  {
    id: "alt-601",
    type: "booking_volume_drop",
    category: "Booking", priority: "P1",
    customerCompanyId: "comp-010",
    title: "API bookings silent — 0 in the last 24h (baseline 12/day)",
    body: "GOTADI's API channel typically delivers ~12 bookings/day. In the past 24h we've received 0. This usually indicates: (1) auth token expired, (2) network/firewall change, (3) upstream booking engine issue. Please verify your integration health.",
    actionLabel: "View API health", actionPath: "/app/bookings?channel=api",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-22 09:00:00",
    refType: "booking",
  },

  /* ══ Booking Volume Anomaly — direct UI (Asia Tours, PREPAY) ══
   * Drop: Asia Tours usually does ~5 bookings/day, but 0 for 3 days straight. */
  {
    id: "alt-602",
    type: "booking_volume_drop",
    category: "Booking", priority: "P1",
    customerCompanyId: "comp-002",
    title: "No bookings for 3 days — baseline 5/day",
    body: "Asia Tours Ltd. has made 0 bookings for 3 consecutive days (2026-04-20 ~ 04-22). Baseline is ~5/day. Is your OP team OK? Are there any login/access issues we can help with?",
    actionLabel: "Contact support", actionPath: "/app/tickets/new",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-22 10:00:00",
    refType: "booking",
  },

  /* ══ Booking Volume Anomaly — API partner spike (Vietnam Vacation Co) ══ */
  {
    id: "alt-603",
    type: "booking_volume_spike",
    category: "Booking", priority: "P1",
    customerCompanyId: "comp-011",
    title: "API spike — 47 bookings in the last hour (baseline 2/hr)",
    body: "Vietnam Vacation Co's API sent 47 booking requests in the last hour. Normal rate is ~2/hr. This may indicate a runaway script, retry storm, or genuine campaign. Rate-limiting has NOT been applied — contact your integration team to confirm.",
    actionLabel: "Review API traffic", actionPath: "/app/bookings?channel=api&filter=1h",
    sentVia: ["In-app", "Email", "SMS"],
    createdAt: "2026-04-23 02:15:00",
    refType: "booking",
  },
];

/* Helper — get unread alerts for a customer */
export function unreadAlertsFor(customerCompanyId: string): Alert[] {
  return alerts.filter(a => a.customerCompanyId === customerCompanyId && !a.readAt && !a.dismissed);
}

/* Helper — get all alerts for a customer (most recent first) */
export function alertsFor(customerCompanyId: string): Alert[] {
  return alerts
    .filter(a => a.customerCompanyId === customerCompanyId && !a.dismissed)
    .sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

/* ── User preferences (per-account) ──
 * In production: stored in user_alert_preferences table.
 * For prototype: simple defaults; UI in My Account → Notifications.
 */
export interface AlertPreference {
  type: AlertType;
  enabled: boolean;
  channels: AlertChannel[];
}

/* Defaults — what every user gets initially.
 * Critical (P0) alerts cannot be fully disabled; only channel toggles allowed. */
export const defaultAlertPreferences: AlertPreference[] = [
  { type: "credit_low",                 enabled: true,  channels: ["In-app", "Email"] },
  { type: "credit_critical",            enabled: true,  channels: ["In-app", "Email", "SMS"] },
  { type: "invoice_overdue",            enabled: true,  channels: ["In-app", "Email"] },
  { type: "topup_confirmed",            enabled: true,  channels: ["In-app", "Email"] },
  { type: "topup_expired",              enabled: true,  channels: ["In-app", "Email"] },
  { type: "prepay_deadline_d7",         enabled: true,  channels: ["In-app", "Email"] },
  { type: "prepay_deadline_d3",         enabled: true,  channels: ["In-app", "Email"] },
  { type: "prepay_deadline_d1",         enabled: true,  channels: ["In-app", "Email"] },
  { type: "prepay_deadline_dday",       enabled: true,  channels: ["In-app", "Email", "SMS"] },
  { type: "booking_auto_cancelled",     enabled: true,  channels: ["In-app", "Email", "SMS"] },
  { type: "booking_cancelled_by_hotel", enabled: true,  channels: ["In-app", "Email", "SMS"] },
  { type: "partial_payment_detected",   enabled: true,  channels: ["In-app", "Email"] },
  { type: "invoice_due_soon",           enabled: true,  channels: ["In-app", "Email"] },
  { type: "topup_pending_reminder",     enabled: true,  channels: ["In-app", "Email"] },
  { type: "invoice_issued",             enabled: true,  channels: ["In-app", "Email"] },
  { type: "payment_received",           enabled: true,  channels: ["In-app"] },
  { type: "dispute_opened",             enabled: true,  channels: ["In-app", "Email"] },
  { type: "dispute_resolved",           enabled: true,  channels: ["In-app", "Email"] },
  { type: "ticket_reply",               enabled: true,  channels: ["In-app"] },
  { type: "checkin_tomorrow",           enabled: false, channels: ["In-app", "Email"] },
  { type: "credit_note_issued",         enabled: true,  channels: ["In-app", "Email"] },
  { type: "subaccount_added",           enabled: true,  channels: ["In-app"] },
  { type: "role_changed",               enabled: true,  channels: ["In-app", "Email"] },
  { type: "contract_amendment",         enabled: true,  channels: ["In-app", "Email"] },
  { type: "points_earned",              enabled: true,  channels: ["In-app"] },
  { type: "points_milestone",           enabled: true,  channels: ["In-app", "Email"] },
  { type: "points_expiring",            enabled: true,  channels: ["In-app", "Email"] },
  { type: "reward_redeemed",            enabled: true,  channels: ["In-app"] },
  { type: "booking_volume_spike",       enabled: true,  channels: ["In-app", "Email"] },
  { type: "booking_volume_drop",        enabled: true,  channels: ["In-app", "Email"] },
];

/* Critical alerts that cannot be fully disabled */
export const undisableableAlerts: AlertType[] = [
  "credit_critical",
  "topup_expired",
  "booking_cancelled_by_hotel",
  "booking_auto_cancelled",
  "prepay_deadline_dday",
];

/* Display metadata per type — used by UI for icons, color, category labels */
export const alertTypeMeta: Record<AlertType, { label: string; category: AlertCategory; priority: AlertPriority }> = {
  credit_low:                 { label: "Credit Low",                   category: "Settlement", priority: "P0" },
  credit_critical:            { label: "Credit Critical",              category: "Settlement", priority: "P0" },
  invoice_overdue:            { label: "Invoice Overdue",              category: "Settlement", priority: "P0" },
  topup_confirmed:            { label: "Top-up Confirmed",             category: "Settlement", priority: "P1" },
  topup_expired:              { label: "Top-up Expired",               category: "Settlement", priority: "P0" },
  prepay_deadline_d7:         { label: "Payment Deadline D-7",         category: "Booking",    priority: "P0" },
  prepay_deadline_d3:         { label: "Payment Deadline D-3",         category: "Booking",    priority: "P0" },
  prepay_deadline_d1:         { label: "Payment Deadline D-1",         category: "Booking",    priority: "P0" },
  prepay_deadline_dday:       { label: "Payment Deadline Today",       category: "Booking",    priority: "P0" },
  booking_auto_cancelled:     { label: "Booking Auto-Cancelled",       category: "Booking",    priority: "P0" },
  booking_cancelled_by_hotel: { label: "Booking Cancelled by Hotel",   category: "Booking",    priority: "P0" },
  partial_payment_detected:   { label: "Partial Payment Detected",     category: "Settlement", priority: "P0" },
  invoice_due_soon:           { label: "Invoice Due Soon (D-2)",       category: "Settlement", priority: "P1" },
  topup_pending_reminder:     { label: "Top-up Pending Reminder (D+5)", category: "Settlement", priority: "P1" },
  invoice_issued:             { label: "Invoice Issued",               category: "Settlement", priority: "P1" },
  payment_received:           { label: "Payment Received",             category: "Settlement", priority: "P1" },
  dispute_opened:             { label: "Dispute Opened",               category: "Dispute",    priority: "P1" },
  dispute_resolved:           { label: "Dispute Resolved",             category: "Dispute",    priority: "P1" },
  ticket_reply:               { label: "Ticket Reply",                 category: "Dispute",    priority: "P1" },
  checkin_tomorrow:           { label: "Check-in Tomorrow",            category: "Booking",    priority: "P1" },
  credit_note_issued:         { label: "Credit Note Issued",           category: "Settlement", priority: "P1" },
  subaccount_added:           { label: "Sub-account Added",            category: "Account",    priority: "P2" },
  role_changed:               { label: "Role Changed",                 category: "Account",    priority: "P2" },
  contract_amendment:         { label: "Contract Amendment",           category: "Account",    priority: "P2" },
  points_earned:              { label: "Points Earned",                category: "Account",    priority: "P2" },
  points_milestone:           { label: "Milestone Reached",            category: "Account",    priority: "P1" },
  points_expiring:            { label: "Points/Voucher Expiring",      category: "Account",    priority: "P1" },
  reward_redeemed:            { label: "Reward Redeemed",              category: "Account",    priority: "P2" },
  booking_volume_spike:       { label: "Booking Volume Spike",         category: "Booking",    priority: "P1" },
  booking_volume_drop:        { label: "Booking Volume Drop",          category: "Booking",    priority: "P1" },
};
