/* Alert system mock.
 *
 * Alerts are derived events surfaced to customers (and potentially admin).
 * In production these would be:
 *   - Generated by ELLIS background workers (cron + event-driven)
 *   - Persisted in alerts table
 *   - Pushed via channels (in-app/email/SMS/Slack)
 *
 * For DOTBIZ prototype, we seed realistic alerts that the customer can
 * see in the Bell icon dropdown / Notifications page.
 *
 * Spec: docs/specs/dotbiz/AlertSystem.md
 */

export type AlertCategory = "Settlement" | "Booking" | "Dispute" | "Account" | "System";

export type AlertPriority = "P0" | "P1" | "P2" | "P3";

export type AlertChannel = "In-app" | "Email" | "SMS" | "Slack";

/* All alert types DOTBIZ supports */
export type AlertType =
  /* P0 — Critical (settlement) */
  | "credit_low"            /* Credit available ≤ Low threshold */
  | "credit_critical"       /* Credit ≤ Critical threshold */
  | "invoice_overdue"       /* POSTPAY invoice past due date */
  | "topup_confirmed"       /* Wire received & matched */
  | "topup_expired"         /* No wire within 7 days */
  | "topup_manual_review"   /* Wire received but ref code missing/wrong */
  /* P0 — Critical (booking) */
  | "prepay_deadline_d7" | "prepay_deadline_d3" | "prepay_deadline_d1" | "prepay_deadline_dday"
  | "booking_cancelled_by_hotel"
  | "partial_payment_detected"
  /* P1 — Important */
  | "invoice_due_soon"       /* D-2 soft reminder before POSTPAY invoice dueDate */
  | "invoice_issued"
  | "payment_received"
  | "dispute_opened"
  | "dispute_resolved"
  | "ticket_reply"
  | "checkin_tomorrow"
  | "booking_confirmed"
  | "credit_note_issued"
  /* P2 — Useful */
  | "subaccount_added"
  | "role_changed"
  | "contract_amendment"
  | "tax_filing_reminder";

export interface Alert {
  id: string;
  type: AlertType;
  category: AlertCategory;
  priority: AlertPriority;
  customerCompanyId: string;
  contractId?: string;     /* Some alerts are contract-scoped */
  title: string;
  body: string;
  /* Action link (deep link inside DOTBIZ) */
  actionLabel?: string;
  actionPath?: string;     /* e.g. /app/settlement/invoice/INV-2026-0089 */
  /* Channels that were sent */
  sentVia: AlertChannel[];
  createdAt: string;
  readAt?: string;
  dismissed?: boolean;
  /* Reference data for the source (so UI can deep-link or rerender) */
  refType?: "invoice" | "booking" | "ticket" | "contract" | "topup";
  refId?: string;
}

/* Seed alerts — covers all P0/P1 types for demo */
export const alerts: Alert[] = [
  /* ── TravelCo (comp-001) — POSTPAY single-contract ── */
  {
    id: "alt-001",
    type: "invoice_overdue",
    category: "Settlement", priority: "P0",
    customerCompanyId: "comp-001", contractId: "ctr-001-sg",
    title: "Invoice INV-2025-0076 is 60+ days overdue",
    body: "USD 29,400 from October 2025 remains unpaid. Please remit immediately to avoid collections team escalation.",
    actionLabel: "View invoice", actionPath: "/app/settlement/invoice/INV-2025-0076",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-19 09:00:00",
    refType: "invoice", refId: "INV-2025-0076",
  },
  {
    id: "alt-002",
    type: "partial_payment_detected",
    category: "Settlement", priority: "P0",
    customerCompanyId: "comp-001", contractId: "ctr-001-sg",
    title: "Partial payment detected on INV-2026-0089",
    body: "Received USD 2,820 against USD 4,180. 2 bookings appear to have been excluded — please confirm via support if any of them are disputed.",
    actionLabel: "View invoice", actionPath: "/app/settlement/invoice/INV-2026-0089",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-15 14:25:00",
    refType: "invoice", refId: "INV-2026-0089",
  },
  {
    id: "alt-003",
    type: "invoice_issued",
    category: "Settlement", priority: "P1",
    customerCompanyId: "comp-001", contractId: "ctr-001-sg",
    title: "New invoice issued: INV-2026-0130 — USD 10,630",
    body: "Your bi-weekly settlement invoice for April 2026 is ready. Due 2026-05-31.",
    actionLabel: "Open invoice", actionPath: "/app/settlement/invoice/INV-2026-0130",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-05-01 01:05:00",
    readAt: "2026-05-01 09:32:11",
    refType: "invoice", refId: "INV-2026-0130",
  },

  /* ── Asia Tours (comp-002) — PREPAY ── */
  {
    id: "alt-010",
    type: "prepay_deadline_dday",
    category: "Booking", priority: "P0",
    customerCompanyId: "comp-002", contractId: "ctr-002-sg",
    title: "Payment due TODAY — Park Hyatt Saigon",
    body: "Booking K26040109301H01 (USD 920) requires payment by 17:00 KST. After deadline, the booking is auto-cancelled.",
    actionLabel: "Pay now", actionPath: "/app/settlement",
    sentVia: ["In-app", "Email", "SMS"],
    createdAt: "2026-04-20 08:00:00",
    refType: "booking", refId: "K26040109301H01",
  },
  {
    id: "alt-011",
    type: "prepay_deadline_d3",
    category: "Booking", priority: "P0",
    customerCompanyId: "comp-002", contractId: "ctr-002-sg",
    title: "Payment due in 3 days — Raffles Singapore",
    body: "Booking K26040816352H01 (USD 1,650) is partially paid. Settle the remaining balance by 2026-04-25.",
    actionLabel: "Pay balance", actionPath: "/app/settlement",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-22 09:00:00",
    refType: "booking", refId: "K26040816352H01",
  },

  /* ── GOTADI (comp-010) — multi-entity, leverage credit (Bank Guarantee) — but Floating, low alert ── */
  {
    id: "alt-020",
    type: "topup_confirmed",
    category: "Settlement", priority: "P1",
    customerCompanyId: "comp-001", contractId: "ctr-001-sg",
    title: "Top-up confirmed: USD +20,000",
    body: "TUP-20260418-A4F7 reconciled. Available credit increased to USD 35,400.",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-19 14:22:08",
    readAt: "2026-04-19 16:00:00",
    refType: "topup", refId: "TUP-20260418-A4F7",
  },
  {
    id: "alt-021",
    type: "credit_low",
    category: "Settlement", priority: "P0",
    customerCompanyId: "comp-010", contractId: "ctr-010-sg",
    title: "Credit running low — only USD 7,200 available",
    body: "Your USD contract with OhMyHotel SG is at 82% utilization. Consider topping up your Floating Deposit before reaching the limit.",
    actionLabel: "Top up", actionPath: "/app/settlement",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-20 06:00:00",
    refType: "contract", refId: "ctr-010-sg",
  },

  /* ── Booking events ── */
  {
    id: "alt-030",
    type: "booking_cancelled_by_hotel",
    category: "Booking", priority: "P0",
    customerCompanyId: "comp-001",
    title: "Hotel cancelled: K26040514508H01 InterContinental Da Nang",
    body: "Hotel reported overbooking. Refund of USD 870 will be processed within 5-7 business days. Apologies for the inconvenience.",
    actionLabel: "View booking", actionPath: "/app/bookings/K26040514508H01",
    sentVia: ["In-app", "Email", "SMS"],
    createdAt: "2026-04-09 11:30:00",
    refType: "booking", refId: "K26040514508H01",
  },
  {
    id: "alt-031",
    type: "checkin_tomorrow",
    category: "Booking", priority: "P1",
    customerCompanyId: "comp-001",
    title: "Check-in tomorrow: 2 guests at Grand Hyatt Seoul",
    body: "John Smith and Sarah Kim arrive 2026-04-21. Hotel confirmation HC-GHS-9821.",
    actionLabel: "View bookings", actionPath: "/app/bookings",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-20 07:00:00",
    readAt: "2026-04-20 08:15:00",
  },
  {
    id: "alt-032",
    type: "booking_confirmed",
    category: "Booking", priority: "P1",
    customerCompanyId: "comp-001",
    title: "Hotel confirmed: K26040816352H01 Raffles Singapore",
    body: "Confirmation code HC-RFL-7723 issued.",
    sentVia: ["In-app"],
    createdAt: "2026-04-09 16:42:11",
    readAt: "2026-04-09 17:01:00",
    refType: "booking", refId: "K26040816352H01",
  },

  /* ── Dispute & ticket ── */
  {
    id: "alt-040",
    type: "dispute_opened",
    category: "Dispute", priority: "P1",
    customerCompanyId: "comp-001",
    title: "Dispute flagged on K26032209155H01 (Shilla Stay Mapo)",
    body: "Reason: Room type mismatch. Linked ticket: TK-2026-007. Our team is investigating.",
    actionLabel: "View ticket", actionPath: "/app/tickets?highlight=TK-2026-007",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-05 11:48:22",
    refType: "ticket", refId: "TK-2026-007",
  },
  {
    id: "alt-041",
    type: "ticket_reply",
    category: "Dispute", priority: "P1",
    customerCompanyId: "comp-001",
    title: "Reply on TK-2026-007",
    body: "Sarah Kim (OP) responded — please review and confirm.",
    actionLabel: "Open ticket", actionPath: "/app/tickets?highlight=TK-2026-007",
    sentVia: ["In-app"],
    createdAt: "2026-04-18 14:30:00",
    refType: "ticket", refId: "TK-2026-007",
  },
  {
    id: "alt-042",
    type: "credit_note_issued",
    category: "Settlement", priority: "P1",
    customerCompanyId: "comp-001",
    title: "Credit note issued: CN-2026-0001 USD -780",
    body: "Issued against INV-2026-0089 for Nikko Bangkok no-show waiver. Will be applied to next bi-weekly invoice.",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-17 15:22:00",
    refType: "invoice", refId: "INV-2026-0089",
  },

  /* ── Account ── */
  {
    id: "alt-050",
    type: "subaccount_added",
    category: "Account", priority: "P2",
    customerCompanyId: "comp-001",
    title: "Sub-account added: emily@travelco.com",
    body: "Role: OP. Added by Master James Park.",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-04-12 10:15:00",
    readAt: "2026-04-12 10:30:00",
  },
  {
    id: "alt-051",
    type: "contract_amendment",
    category: "Account", priority: "P2",
    customerCompanyId: "comp-001", contractId: "ctr-001-sg",
    title: "Settlement cycle changed: Monthly → Bi-weekly",
    body: "Effective from 2026-04-01, payment due days shortened from Net-14 to Net-5 (issued Bi-weekly). Contact your account manager with questions.",
    sentVia: ["In-app", "Email"],
    createdAt: "2026-03-25 09:00:00",
    readAt: "2026-03-25 11:00:00",
  },
];

/* Helper — get unread alerts for a customer */
export function unreadAlertsFor(customerCompanyId: string): Alert[] {
  return alerts.filter(a => a.customerCompanyId === customerCompanyId && !a.readAt && !a.dismissed);
}

/* Helper — get all alerts for a customer (most recent first) */
export function alertsFor(customerCompanyId: string): Alert[] {
  return alerts
    .filter(a => a.customerCompanyId === customerCompanyId && !a.dismissed)
    .sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

/* ── User preferences (per-account) ──
 * In production: stored in user_alert_preferences table.
 * For prototype: simple defaults; UI in My Account → Notifications.
 */
export interface AlertPreference {
  type: AlertType;
  enabled: boolean;
  channels: AlertChannel[];
}

/* Defaults — what every user gets initially.
 * Critical (P0) alerts cannot be fully disabled; only channel toggles allowed. */
export const defaultAlertPreferences: AlertPreference[] = [
  { type: "credit_low",                 enabled: true,  channels: ["In-app", "Email"] },
  { type: "credit_critical",            enabled: true,  channels: ["In-app", "Email", "SMS"] },
  { type: "invoice_overdue",            enabled: true,  channels: ["In-app", "Email"] },
  { type: "topup_confirmed",            enabled: true,  channels: ["In-app", "Email"] },
  { type: "topup_expired",              enabled: true,  channels: ["In-app", "Email"] },
  { type: "topup_manual_review",        enabled: true,  channels: ["In-app", "Email"] },
  { type: "prepay_deadline_d7",         enabled: true,  channels: ["In-app", "Email"] },
  { type: "prepay_deadline_d3",         enabled: true,  channels: ["In-app", "Email"] },
  { type: "prepay_deadline_d1",         enabled: true,  channels: ["In-app", "Email"] },
  { type: "prepay_deadline_dday",       enabled: true,  channels: ["In-app", "Email", "SMS"] },
  { type: "booking_cancelled_by_hotel", enabled: true,  channels: ["In-app", "Email", "SMS"] },
  { type: "partial_payment_detected",   enabled: true,  channels: ["In-app", "Email"] },
  { type: "invoice_due_soon",           enabled: true,  channels: ["In-app", "Email"] },
  { type: "invoice_issued",             enabled: true,  channels: ["In-app", "Email"] },
  { type: "payment_received",           enabled: true,  channels: ["In-app"] },
  { type: "dispute_opened",             enabled: true,  channels: ["In-app", "Email"] },
  { type: "dispute_resolved",           enabled: true,  channels: ["In-app", "Email"] },
  { type: "ticket_reply",               enabled: true,  channels: ["In-app"] },
  { type: "checkin_tomorrow",           enabled: false, channels: ["In-app", "Email"] },
  { type: "booking_confirmed",          enabled: false, channels: ["In-app"] },
  { type: "credit_note_issued",         enabled: true,  channels: ["In-app", "Email"] },
  { type: "subaccount_added",           enabled: true,  channels: ["In-app"] },
  { type: "role_changed",               enabled: true,  channels: ["In-app", "Email"] },
  { type: "contract_amendment",         enabled: true,  channels: ["In-app", "Email"] },
  { type: "tax_filing_reminder",        enabled: false, channels: ["In-app"] },
];

/* Critical alerts that cannot be fully disabled */
export const undisableableAlerts: AlertType[] = [
  "credit_critical",
  "topup_expired",
  "booking_cancelled_by_hotel",
  "prepay_deadline_dday",
];

/* Display metadata per type — used by UI for icons, color, category labels */
export const alertTypeMeta: Record<AlertType, { label: string; category: AlertCategory; priority: AlertPriority }> = {
  credit_low:                 { label: "Credit Low",                   category: "Settlement", priority: "P0" },
  credit_critical:            { label: "Credit Critical",              category: "Settlement", priority: "P0" },
  invoice_overdue:            { label: "Invoice Overdue",              category: "Settlement", priority: "P0" },
  topup_confirmed:            { label: "Top-up Confirmed",             category: "Settlement", priority: "P1" },
  topup_expired:              { label: "Top-up Expired",               category: "Settlement", priority: "P0" },
  topup_manual_review:        { label: "Top-up Manual Review",         category: "Settlement", priority: "P0" },
  prepay_deadline_d7:         { label: "Payment Deadline D-7",         category: "Booking",    priority: "P0" },
  prepay_deadline_d3:         { label: "Payment Deadline D-3",         category: "Booking",    priority: "P0" },
  prepay_deadline_d1:         { label: "Payment Deadline D-1",         category: "Booking",    priority: "P0" },
  prepay_deadline_dday:       { label: "Payment Deadline Today",       category: "Booking",    priority: "P0" },
  booking_cancelled_by_hotel: { label: "Booking Cancelled by Hotel",   category: "Booking",    priority: "P0" },
  partial_payment_detected:   { label: "Partial Payment Detected",     category: "Settlement", priority: "P0" },
  invoice_due_soon:           { label: "Invoice Due Soon (D-2)",       category: "Settlement", priority: "P1" },
  invoice_issued:             { label: "Invoice Issued",               category: "Settlement", priority: "P1" },
  payment_received:           { label: "Payment Received",             category: "Settlement", priority: "P1" },
  dispute_opened:             { label: "Dispute Opened",               category: "Dispute",    priority: "P1" },
  dispute_resolved:           { label: "Dispute Resolved",             category: "Dispute",    priority: "P1" },
  ticket_reply:               { label: "Ticket Reply",                 category: "Dispute",    priority: "P1" },
  checkin_tomorrow:           { label: "Check-in Tomorrow",            category: "Booking",    priority: "P1" },
  booking_confirmed:          { label: "Booking Confirmed",            category: "Booking",    priority: "P1" },
  credit_note_issued:         { label: "Credit Note Issued",           category: "Settlement", priority: "P1" },
  subaccount_added:           { label: "Sub-account Added",            category: "Account",    priority: "P2" },
  role_changed:               { label: "Role Changed",                 category: "Account",    priority: "P2" },
  contract_amendment:         { label: "Contract Amendment",           category: "Account",    priority: "P2" },
  tax_filing_reminder:        { label: "Tax Filing Reminder",          category: "Settlement", priority: "P2" },
};
